### ISSUE TITLE
San Sebastian ( Donostia ) Spain

### ISSUE THREAD

**Issue by joriswu** [OpenMobilityData/OpenMobilityData-Public#114]
San Sebastian ( Donostia in Basque ) is here

ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/ATTG/dbus/google_transit.zip

Coverage map is here

http://www.dbus.eus/dbus-en-mugitzea/lineas-y-horarios

ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/* shows a handful of smaller feeds from regional Basque towns.

Basque part of railways are here

ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/ATTG/renfe/google_transit.zip

**Comment by joriswu** [comment]
Is there  any reason this feed iks not yet added ?

**Comment by HendX** [comment]
Sorry @joriswu, just hadn't got to it yet. Will look at it tomorrow.

**Comment by HendX** [comment]
Here's the full list of URLs on that (extremely slow) FTP site:

ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Alavabus/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/ATTG/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Bilbobus/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Bizkaibus/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Euskotren/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/FunicularArtxanda/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/La_Burundesa/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/La_Union/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/MetroBilbao/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/Transbordador_Vizcaya/google_transit.zip
ftp://ftp.geo.euskadi.net/cartografia/Transporte/Moveuskadi/TUVISA/google_transit.zip

**Comment by HendX** [comment]
I've added dBus here (the "ATTG" feed):
http://transitfeeds.com/p/compania-del-tranvia-de-san-sebastian/702

I'll leave this open for now until the remainder of the feeds are added
