### ISSUE TITLE
Ireland

### ISSUE THREAD

**Issue by joriswu** [OpenMobilityData/OpenMobilityData-Public#115]
All feeds for Ireland can be found under http://www.transportforireland.ie/transitData/PT_Data.html

Highlights are: Dublin Bus, Irish Rail, Bus Eireann

**Comment by HendX** [comment]
Do you think it's reasonable just to put them all under "Ireland", or split them by location within Ireland?

**Comment by joriswu** [comment]
I suggest to keep the larger items separate, and set all smaller towns under 'ireland'

Dublin   http://www.transportforireland.ie/transitData/google_transit_dublinbus.zip

Irish Railways   http://www.transportforireland.ie/transitData/google_transit_irishrail.zip

Bus Éireann (operates cross-country) http://www.transportforireland.ie/transitData/google_transit_buseireann.zip

And the rest is all 'ireland;' as you suggest

**Comment by BobHarper1** [comment]
Ireland not showing under Europe http://transitfeeds.com/l/60-europe

Also impressed to see Texas as it's own continent ;)

**Comment by HendX** [comment]
Hi @BobHarper1 - I haven't added the Irish feeds yet, sorry about this.

I also fixed the Texas issue.

**Comment by HendX** [comment]
Dublin added here: http://transitfeeds.com/p/transport-for-ireland

**Comment by BobHarper1** [comment]
Fantastic, thank you

**Comment by stevevance** [comment]
All of the feeds hosted on http://www.transportforireland.ie/transitData/PT_Data.html are now giving cURL a problem of too many redirects. 

````
* Closing connection 50
* Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
````

Dos anyone have a contact at Transport for Ireland?
