### ISSUE TITLE
GTFS Sncf

### ISSUE THREAD

**Issue by stebazzi** [OpenMobilityData/OpenMobilityData-Public#124]
Here you can find different GTFS files about french railway service:
http://medias.sncf.com/sncfcom/open-data/gtfs/export-INTERCITES-GTFS-LAST.zip
http://medias.sncf.com/sncfcom/open-data/gtfs/export-TER-GTFS-LAST.zip
http://medias.sncf.com/sncfcom/open-data/gtfs/export-TRAM-TRAIN-TER-PDL-GTFS-LAST.zip
about the high-speed trains could not find anything.

Thanks

**Comment by joriswu** [comment]
Note that some feeds, especially Lignes TER, have a handful of stops with coordinates in the Algerian desert. I have been in touch with SNCF, they acknowledge but report that this will not be fixed soon.
