### ISSUE TITLE
Department of Roads Transport and Safety, Botswana.. Feeds generated by GDG Gaborone

### ISSUE THREAD

**Issue by kesegotumisang** [OpenMobilityData/OpenMobilityData-Public#133]
http://gdggaborone.org/agency.zip or
http://gdggaborone.org/agency.klm

**Comment by bufemc** [comment]
Unfortunately throws (meanwhile?) a http 404 not found, is there a replacement?
Did not find any on http://www.gov.bw/ (yet).
