### ISSUE TITLE
Add Tri-Rail in South Florida

### ISSUE THREAD

**Issue by qtrandev** [OpenMobilityData/OpenMobilityData-Public#147]
http://www.tri-rail.com/GTDF/Current/google_transit.zip

They have real-time tracking for their trains, but no developer website.
http://www.tri-rail.com/tri-rail-tracker/

Tri-Rail runs from Palm Beach County, to Broward County, and to Miami-Dade County.
They are based in Pompano Beach, FL (near Fort Lauderdale, FL).
http://www.tri-rail.com/contact-us/

**Comment by fede843** [comment]
Hi, so realtime stuff there is just an customer app?

**Comment by qtrandev** [comment]
Yes, mobile app and a web app, nothing like GTFS-realtime that I know off yet.

**Comment by fede843** [comment]
That's fine. Thanks!

**Comment by mldickens** [comment]
Cool, I've added it.

**Comment by mldickens** [comment]
http://transitfeeds.com/p/south-florida-regional-transportation-authority/699
