### ISSUE TITLE
Finland data

### ISSUE THREAD

**Issue by kemkim** [OpenMobilityData/OpenMobilityData-Public#149]
Finnish public transport data
- [X] City of Tampere
  http://data.itsfactory.fi/files/tampere_gtfs_latest.zip
- [X] City of Jyväskylä
  http://data.jyvaskyla.fi/tiedostot/linkkidata.zip
- [X] City of Oulu
  http://www.transitdata.fi/oulu/google_transit.zip
- [X] City of Turku
  http://data.foli.fi/gtfs/gtfs.zip
- [X] City of Kuopio
  http://bussit.kuopio.fi/gtfs/gtfs.zip
- [X] City of Joensuu
  http://dev.hsl.fi/gtfs.waltti/joensuu.zip
- [X] North Karelia province
  http://dev.hsl.fi/gtfs.waltti/posjoe.zip
- [X] Ferries
  http://lautta.net/db/gtfs/gtfs.zip
- [x] Helsinki capital region
  http://dev.hsl.fi/gtfs/hsl.zip
- [ ] Waltti (public service obligation in North Karelia)
  http://dev.hsl.fi/gtfs.waltti/207.zip
  http://dev.hsl.fi/gtfs.waltti/183.zip
- [ ] Finland long distance public transport
  http://dev.hsl.fi/gtfs.matka/matka.zip"

**Comment by patrickbr** [comment]
Hi there,

just my two cents: the long distance public transport feed (MATKA) is invalid. There are some entries in stop_times.txt where the departures time is smaller than the arrival time.

patrick

**Comment by kemkim** [comment]
Hello

Matka.fi timetable information is known to be of bad quality, but it is the
only GTFS which we have of long-distance public transport in Finland. But
if it is not good enough, you can leave it aside and keep other Finnish
GTFS schedules.

Kimmo Kemppainen
15.6.2016 8.25 ip. "Patrick Brosi" <notifications@github.com> kirjoitti:

**Comment by fede843** [comment]
Hello, do you know which one of them are providing real time feed?

**Comment by HendX** [comment]
Thanks - will update as I add each one.

City of Tampere: https://transitfeeds.com/p/tampereen-joukkoliikenne/727

**Comment by HendX** [comment]
City of Jyväskylä: https://transitfeeds.com/p/city-of-jyvaskyla/728

**Comment by HendX** [comment]
City of Oulu: https://transitfeeds.com/p/oulun-joukkoliikenne/729

**Comment by HendX** [comment]
City of Turku: https://transitfeeds.com/p/city-of-turku/730

**Comment by HendX** [comment]
City of Kuopio: https://transitfeeds.com/p/city-of-kuopio/731

**Comment by HendX** [comment]
City of Joensuu: https://transitfeeds.com/p/city-of-joensuu/732

**Comment by HendX** [comment]
North Karelia: https://transitfeeds.com/p/liikennevirasto/733

**Comment by HendX** [comment]
Ferries: https://transitfeeds.com/p/ferries/734

**Comment by HendX** [comment]
Helsink: https://transitfeeds.com/p/helsinki-regional-transport/735

**Comment by HendX** [comment]
Notes:

* I'm unsure how to list the Waltti feeds, so haven't yet included them (what's the difference between the two feeds?)

* I've omitted the MATKA feed for now

* I'm not confident with how I've categorised the feeds. For example, I don't think the provider names and feed names are the best - It would be good to have them under their actual data providers. For example, I couldn't determine if Liikennevirasto is the main "department of transport" and all feeds should list under there.

Any help or feedback is appreciated.

**Comment by tuukka** [comment]
Hi! I maintain dev.hsl.fi. I've just added new feeds under http://dev.hsl.fi/gtfs.waltti/ They are not of as good quality as the feeds provided by some of the cities themselves, so it should be only used as a fallback. (Waltti http://waltti.fi/?lang=en is the ticketing system run together by the Finnish cities and regions excluding the Helsinki region.)

183 and 207 are old names and should not be listed. posjoe is an old name replaced by posely_joensuu.

Liikennevirasto is Finnish Transport Agency (http://fta.fi/). They don't produce any local or regional data themselves but they gather all the data into a national feed (MATKA). The national government produces data via the regional ELYs such as North Savo ELY (which happens to cover North Karelia as well).

Central Finland ELY: http://dev.hsl.fi/gtfs.waltti/keski-suomen_ely.zip
North Ostrobothnia ELY: http://dev.hsl.fi/gtfs.waltti/pohjois-pohjanmaan_ely.zip
North Savo ELY (divided into four subregion feeds):
http://dev.hsl.fi/gtfs.waltti/posely_iisalmi.zip
http://dev.hsl.fi/gtfs.waltti/posely_joensuu.zip
http://dev.hsl.fi/gtfs.waltti/posely_kuopio.zip
http://dev.hsl.fi/gtfs.waltti/posely_mikkeli.zip

Some newly available cities:
http://dev.hsl.fi/gtfs.waltti/hameenlinna.zip (Hämeenlinna)
http://dev.hsl.fi/gtfs.waltti/kajaani.zip
http://dev.hsl.fi/gtfs.waltti/kotka.zip
http://dev.hsl.fi/gtfs.waltti/kvl.zip (Kouvola)
http://dev.hsl.fi/gtfs.waltti/lahti.zip
http://dev.hsl.fi/gtfs.waltti/lappeenranta.zip
http://dev.hsl.fi/gtfs.waltti/mikkeli.zip
http://dev.hsl.fi/gtfs.waltti/vaasa.zip
