### ISSUE TITLE
Madrid Region transport authoritie feed (GFTS) [Spain]

### ISSUE THREAD

**Issue by ciudadrealbus** [OpenMobilityData/OpenMobilityData-Public#155]
Last week, the CRTM (Madrid Region transport authorite) has released his opendata website. Here are the links of the differents means of transport.
- [x] Metro (underground): http://crtm.maps.arcgis.com/home/item.html?id=5c7f2951962540d69ffe8f640d94c246
- [ ] EMT (Madrid city local buses): http://crtm.maps.arcgis.com/home/item.html?id=868df0e58fca47e79b942902dffd7da0
- [ ] Urbanos municipios (Other cities local buses): http://crtm.maps.arcgis.com/home/item.html?id=357e63c2904f43aeb5d8a267a64346d8
- [ ] Interurbanos (Madrid regional buses): http://crtm.maps.arcgis.com/home/item.html?id=885399f83408473c8d815e40c5e702b7
- [x] Metro ligero (light rail): http://crtm.maps.arcgis.com/home/item.html?id=aaed26cc0ff64b0c947ac0bc3e033196
- [ ] Cercanías (regional trains): http://crtm.maps.arcgis.com/home/item.html?id=1a25440bf66f499bae2657ec7fb40144

**Comment by HendX** [comment]
Metro added:
https://transitfeeds.com/p/consorcio-regional-de-transportes-de-madrid/742

**Comment by HendX** [comment]
@ciudadrealbus we already have EMT here: https://transitfeeds.com/p/emt-madrid

Should we update to this new link?

**Comment by HendX** [comment]
Metro Ligero added:
https://transitfeeds.com/p/consorcio-regional-de-transportes-de-madrid/743

**Comment by fede843** [comment]
Hi, noticed "Urbanos municipios" and "Interurbanos" end up being same file. They are named google_transit_M9.zip and google_transit_M89.zip but they are the same file, same content. Are they supposed to be the same?

**Comment by ciudadrealbus** [comment]
@HendX the link from EMT its from the bus company, and the link above is from the transport authoritie. The data should be the same.

@fede843 It's should be different. If you check the routes file, "interurbanos" lines are the ones which start with "8", and "urbanos municipios" the ones which start with 9. I don't know why they put the information in the same file. Maybe because there are some companys which opperate in both networks. You can contact with the authoritie for more information contacto@crtm.es Let me know if you need some help with the spanish

**Comment by fede843** [comment]
Thanks @ciudadrealbus. I'll do contact them, just to let them know.

**Comment by adavidzh** [comment]
@HendX, I was wondering why the "Cercanías" was not added.
The interface seems identical for all six datasets in http://data-crtm.opendata.arcgis.com/
