### ISSUE TITLE
List of locations getting very long

### ISSUE THREAD

**Issue by HendX** [OpenMobilityData/OpenMobilityData-Public#164]
On the side bar, there's a large number of locations in some areas, such as California:

https://transitfeeds.com/l/67-california-usa

The sidebar should be collapsed or collapsable in some way.

**Comment by caywood** [comment]
California is a big place. I think this behavior is OK for a site that's targeted at developers and power users, but would accept a patch that would start default collapsed, then give you an highly visible expand button.
