### ISSUE TITLE
Italy > Bologna

### ISSUE THREAD

**Issue by atomotic** [OpenMobilityData/OpenMobilityData-Public#168]
Bus service in Bologna ([ATC](https://www.tper.it/tper-open-data)) has GTFS downloadable [here](https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=tper.it&filename=gommagtfsbo&version=20160629&format=zip)

**Comment by joriswu** [comment]
Note 1: this is not a static URL
Note 2: I get errors when downloading from a script. Browser download is OK.

**Comment by atomotic** [comment]
`~ curl -s -I "https://solweb.tper.it/web/tools/open-data/open-data-download.aspx?source=tper.it&filename=gommagtfsbo&version=20160629&format=zip" | grep Location`

`Location: /resources/files/opendata/gommagtfsbo_20160629.zip`

so [https://solweb.tper.it/resources/files/opendata/gommagtfsbo_20160629.zip](https://solweb.tper.it/resources/files/opendata/gommagtfsbo_20160629.zip) seems a better url

**Comment by matricola12** [comment]
Bus service in Bologna ([TPER](http://www.tper.it)) has GTFS downloadable [here](http://www.boologna.it/gtfs/gommagtfsbo.zip).

It is the same GTFS of "https://solweb.tper.it/resources/files/opendata/gommagtfsbo_**yyyymmdd**.zip", but in a static url.

This GTFS has one or two day of delay.

It is used [transit.land](https://transit.land/).

**Comment by fede843** [comment]
Hi, I know it's not the same city but it's same operator and they are neighbors. TPER for Ferrara is hosted in solweb.tper.it too and it has a variable link. By chance do you know if there is a permanent one of it?

**Comment by matricola12** [comment]
Hello, I am not aware of a static site for GTFS of Ferrara. The GTFS Bologna I transfer them from TPER website to my website.

**Comment by fede843** [comment]
Thanks for replying. Cheers!
