### ISSUE TITLE
Recent Added List Too Short

### ISSUE THREAD

**Issue by RideSchedules** [OpenMobilityData/OpenMobilityData-Public#169]
The Recently Added Feeds list is too short to get a complete view of what's been added within the past couple of months. 

View More should point to a list sorted by date added.

**Comment by HendX** [comment]
Thanks - I'll have a think about the best way to achieve this.

**Comment by caywood** [comment]
IMO this feature is just there to help people understand we are adding feeds all the time, and maybe give them a good feeling if they added it. You can always use the API to look at a more comprehensive list of latest feeds.
