### ISSUE TITLE
Durham Region Transit issues

### ISSUE THREAD

**Issue by useless2764** [OpenMobilityData/OpenMobilityData-Public#172]
#1. Url changed to https://maps.durham.ca/OpenDataGTFS/GTFS_Durham_TXT.zip
#2. City should probably be set to Oshawa, ON and not Durham, ON

**Comment by mldickens** [comment]
How were you aware of the URL change? Do they have a developer page or something?

Will see if we can change the location.

**Comment by unforgettableid** [comment]
Regarding point 2 by @danmackay:

"Durham, ON" is probably wrong, but "Oshawa, ON" is also probably wrong. The feed covers all of Durham Region, and Oshawa is only one part of Durham Region.

"Durham Region, ON" would probably be more correct.
