### ISSUE TITLE
Some GTFS Italy

### ISSUE THREAD

**Issue by stebazzi** [OpenMobilityData/OpenMobilityData-Public#184]
Please add:
- [x] Region Marche 
- http://www.trasporti.marche.it/downloads/opendata/GTFS_TRASPORTI_UNIFICATO_13-07-2016.zip
- [x] Florence
- http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/a53a10ae-4d08-4f41-a9d0-0b99826ff00c/download/ataflinea.gtfs
- Added: https://transitfeeds.com/p/azienda-trasporti-dellarea-fiorentina/739
- [ ] Piombino
- http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/f9b10e12-9a8c-4161-83ca-dec377d739f7/download/tiemme.gtfs
- Returned a 404
- [x] Mugello
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/d2e112e1-1669-480f-bb9b-fa25bd13a2db/download/amvbus.gtfs
- [ ] Pistoia
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/54ecb654-e3c0-4935-82b7-7c9a47541883/download/blubus.gtfs
- [ ] Prato
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/4dba30d7-4a25-41b3-af48-0509c6cb5e8f/download/cap.gtfs
- [ ] Livorno
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/928f7151-acae-4f1f-8cde-b589a6c98ba2/download/ctt.gtfs
- [ ] Lucca
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/b8bb4472-35c8-45bf-a4f8-f8beb1c07fc7/download/vaibus.gtfs
- [ ] Toremar
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/ad82f56d-7bd9-4695-bc56-4a0e134e09cf/download/toremar.gtfs
- [ ] Chianti
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/73b3f33e-51cd-4155-90b6-637f72e908d4/download/acvbus.gtfs
- [x] Ferrovie Toscana
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/3e875901-02f6-4517-968a-01bae15df7c8/download/tft.gtfs
- [x] Trenitalia DTR Toscana
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/6fa3e2a7-14df-430c-814e-e8d2aa2d8f0f/download/trenitalia.gtfs
- [ ] Gest
  http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/aa1a80df-44d7-46b2-a7c9-58e0f9ab6273/download/gest.gtfs

Many thanks

**Comment by HendX** [comment]
Related to #168 and #180 - I'm planning to add all of these very soon.

**Comment by HendX** [comment]
Mugello added here: https://transitfeeds.com/p/autolinee-mugello-valdisieve/750

**Comment by stebazzi** [comment]
Dear HendX
All Tuscany links are updated:
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/0a8e7c64-2314-4732-849a-67746b8a0eba/download/tft.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/ad82f56d-7bd9-4695-bc56-4a0e134e09cf/download/toremar.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/277c6f2d-0ed1-4a47-9a99-cfcaf6b1e25f/download/trenitalia.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/543d042c-027f-4503-8ca4-893d338415e3/download/piubus.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/2d6470ba-a0dc-48cc-8f29-9e6e10f469f0/download/ctt.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/34c2d603-4672-4e2f-98d9-3d7df65c6ffe/download/cap.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/6fd6b701-d683-4b22-ad94-67c7a9fe3a1a/download/blubus.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/a52ca509-9b87-4a23-a7db-35197e7c59da/download/ataflinea.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/55af5ceb-2209-4c66-a4a3-49fd8f9b1fc3/download/gest.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/7e4ca15c-4ab1-4dce-bc29-91de70cdc9b6/download/acvbus.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/6e71e2c5-0410-4b1f-a3fe-05b72bd0cc16/download/etruriamobilita.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/9e98c358-6e1d-4e27-af48-43a03cd8e8e7/download/sienamobilita.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/287d466b-706f-4877-8e9d-c69ae2417b92/download/amvbus.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/9fe5fa0d-dfbc-49e2-a840-427c17f15d2f/download/cpt.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/c14713ca-3c84-4299-9f8b-3cc2ff3d5206/download/vaibus.gtfs
http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/8e378df5-31f4-4194-a9eb-aa704e9c772e/download/tiemme.gtfs

Thanks

**Comment by stebazzi** [comment]
Also Marche is updated:
http://www.trasporti.marche.it/downloads/opendata/GTFS_TRASPORTI_UNIFICATO_21-12-2016.zip
Now I write to authors to create static url

**Comment by fabiodaniele** [comment]
Hi all,
I hope this helps: I just found this for the city of Naples, containing all the data about **Azienda Napoletana Mobilità**, one of the public transport companies in the city

[http://www.comune.napoli.it/flex/cm/pages/ServeAttachment.php/L/IT/D/7%252F7%252F8%252FD.e5b37c8c7db672d9332d/P/BLOB%3AID%3D29233/E/zip](http://www.comune.napoli.it/flex/cm/pages/ServeAttachment.php/L/IT/D/7%252F7%252F8%252FD.e5b37c8c7db672d9332d/P/BLOB%3AID%3D29233/E/zip)
