### ISSUE TITLE
PATCO (NJ) Updated as of October 22

### ISSUE THREAD

**Issue by mfs1013** [OpenMobilityData/OpenMobilityData-Public#201]
http://www.ridepatco.org/developers/PortAuthorityTransitCorporation20161022.zip

**Comment by fede843** [comment]
Hello, is this link not working any more? http://www.ridepatco.org/developers/PortAuthorityTransitCorporation.zip

**Comment by mfs1013** [comment]
The timetable was just updated on Saturday

Try here http://www.ridepatco.org/developers/

**Comment by fede843** [comment]
it's really a pity they don't use a permanent link anymore

**Comment by mfs1013** [comment]
At least they can notify developers when a new GTFS is released
