### ISSUE TITLE
getCurrentFeedVersion request

### ISSUE THREAD

**Issue by markerpen** [OpenMobilityData/OpenMobilityData-Public#202]
There's an issue at the moment where Translink (Vancouver)'s latest GTFS feed doesn't start until 19 December 2016. Unfortunately this means that the **getLatestFeedVersion** endpoint brings back a GTFS feed that won't show any stop times yet.

Is there a possibility of adding a new endpoint - something like **getCurrentFeedVersion** which brings back the currently-active GTFS feed rather than the latest feed?

If that's not possible, can a flag be added to **getFeeds** to let us know if a feed hasn't started yet, or showing a feed's effective start/end date? This info appears on the feed's TransitFeeds webpage (https://transitfeeds.com/p/translink-vancouver/29/latest) but not within the API.

Many thanks in advance.

**Comment by HendX** [comment]
Hi @markerpen, thanks for the request.

I've added the start/finish dates to the response data of `getFeedVersions`, as requested. It's in the `d.s` and `d.f` elements. The documentation has been updated here to include it:

https://transitfeeds.com/api/swagger/#!/default/getFeedVersions

You could query this with the specific feed to determine which one you're after.

Let me know how this goes for you, then we can gauge if an extra endpoint or option is necessary.

**Comment by markerpen** [comment]
Quick work and works great - thank you so much!
