### ISSUE TITLE
Omaezaki problem

### ISSUE THREAD

**Issue by miolu66** [OpenMobilityData/OpenMobilityData-Public#207]
I see that there is no calendar.txt for the Omaezaki feed. In the mean time all the entries in the calendar_dates.txt are marked with exception_type = 2 (removed). How is it possible for this feed to be valid?

**Comment by HendX** [comment]
Hi @miolu66 - The feed validator on TransitFeeds doesn't take into account that kind of logic, but the structure of the file is technically correct.
