### ISSUE TITLE
GTFS Transjogja bus routes from Yogyakarta, Indonesia

### ISSUE THREAD

**Issue by capiscuas** [OpenMobilityData/OpenMobilityData-Public#210]
Hi, here is the Yogyakarta bus routes GTFS, I created the transit routes in OSM and autogenerated the GTFS from it using an script.
[google_transit.zip](https://github.com/TransitFeeds/TransitFeeds-Public/files/701594/google_transit.zip)

[transjogja.py.txt](https://github.com/TransitFeeds/TransitFeeds-Public/files/701595/transjogja.py.txt)

What are the stepts to include it in the transitfeeds?

**Comment by HendX** [comment]
I can add it - however, how frequently is that updated? It looks over a year out of date.

**Comment by capiscuas** [comment]
That would be great, thanks. 
Routes and stops hasn't changed since. The timetables are estimations from the official initial hour to closing hour.
Best Regards.
