### ISSUE TITLE
Feed Licensing Support in API

### ISSUE THREAD

**Issue by ghost** [OpenMobilityData/OpenMobilityData-Public#231]
Creating or sharing maps that contain multiple data Feeds is difficult when manual review of each feed source is required in order to identify the provider’s usage constraints. This can be a legal minefield, one that people are not typically willing to navigate.

It would be a great help to include license restriction/usage fields in the JSON data for each Feed.

- These fields should cover ‘attribution’, ‘redistribution’, creating ‘product derivatives’, and other rights.
- These fields should clearly indicating whether or not the consumer has the permissions to access or share the content and what is required to do so.
- They should also include provisions for a specified licensing URL and/or licensing type (commercial, public, open data, …).

As a secondary suggestion, it would be helpful is the web page(s) that list the Feeds can be augmented to reflect this information. Helping consumers quickly locate feeds that fit their requirements.

**Comment by HendX** [comment]
Thanks @iamsinistar - I think this would be extremely useful.

As it stands, there's a single URL field available for each feed to list the feed, but I like the suggestion of a list of permissions (for lack of better term) for each feed.

Other than attribution, redistribution and creating derivatives, are there any others you think that would be of use?

**Comment by iamsinistar** [comment]
Hey Quentin,

Great to have the chance to collaborate on this. It would be a huge improvement for all potential consumers to understand the licensing that each provider selects/allows.

Here’s the details from our legal team that gives us some direction on what we can and cannot consume based on the Creative Commons<https://urldefense.proofpoint.com/v2/url?u=https-3A__creativecommons.org_share-2Dyour-2Dwork_licensing-2Dtypes-2Dexamples_&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=kCFIXDlJnmeXdj1FZisJ6JGyXZ1BdPmJTWsL8gSIUvwXRgWipss3gRp_LxxlalgfJyKgyuuC_J7hmFz3UqkARzfuptWdlB04V0B5r7cFyWWSmHoO71qj1L30qXQbXvvYVrz9n-CutgUeoEw38dtRCw&m=piZ8bQmY8F8VT54LDdVqnxyN3iZUlqNqUfzfdRH8bwE&s=g0Qq-5I7k8VQ0Lf8gbg2nvDyz_UeJAaMwv5k65zv9mo&e= > guidelines:

-----------------------------------
There’s a few creative commons attributions that "available for commercial use” falls under:
•             Public Domain (CC0): Freeing content globally without restrictions
•             Attribution Along (CC BY): This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.
•             Attribution + ShareAlike (CC BY-SA): This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. This license is often compared to “copyleft” free and open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. This is the license used by Wikipedia, and is recommended for materials that would benefit from incorporating content from Wikipedia and similarly licensed projects.
•             Attribution + NoDerivatives (CC BY-ND): Licensees may copy, distribute, display and perform only verbatim copies of the work, not derivative works and remixes based on it.
The ones that are not for commercial use include:
•             Attribution + Noncommercial (CC BY-NC): This license lets others remix, tweak, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don’t have to license their derivative works on the same terms.
•             Attribution + Noncommercial + ShareAlike (CC BY-NC-SA): This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.
•             Attribution + Noncommercial + NoDerivatives (CC BY-NC-ND): This license is the most restrictive of our six main licenses, only allowing others to download your works and share them with others as long as they credit you, but they can’t change them in any way or use them commercially.
-----------------------------------

My thought is that you could present a series of selections to the Provider when they contribute or update a feed.


-          Picking between [‘Public Domain’ (CC0) the default, ‘Non-Commercial only’ (CC NC), and ‘Commercial use okay’ (CC)]

And if not Public Domain, they could refine by having access to:

-          Augmented by selecting [‘Attribution Along’ (BY) which is the default for non-CC0, ‘Attribution plus ShareAlike’ (BY-SA), and ‘Attribution plus NoDerivatives’ (BY-ND)]

All of the above should include help links to the Creative Commons web site for clarification.

On the consumer side, the feed API could return the details as a single JSON key/value pair with the abbreviated license details the provider selected, like:

-          {“license”: “CC0”}

-          {“license”: “CC BY-NC-SA”}

That should make it simple for folks to navigate and minimize the overhead, reducing the confusion while providing the licensing detail required.

What do you think?

Paul

**Comment by HendX** [comment]
Thanks @iamsinistar - I'm working very slowly currently but I'll get to this soon ;)
