### ISSUE TITLE
Feature Request: Latest Current Routes page.

### ISSUE THREAD

**Issue by 3vivekb** [OpenMobilityData/OpenMobilityData-Public#233]
I think #232  leads to a feature request:
Instead of just have a category as "Latest Download" you should also have a category called "Latest Current Routes".  
1.  Sometimes an agency will publish a gtfs that doesn't apply to today but for say a week from now.  At that point it is the latest download but it doesn't show up with Latest Current Routes.  When the date gets to when the new gtfs applies, it becomes the latest current routes as well as the Latest download.

2.  Sometimes an agency will post a new gtfs updating their current routes even though the previous gtfs has not expired.  Then that gtfs will be categorized as both the latest download as well as the Latest Current Routes.

**Comment by HendX** [comment]
Thanks for the suggestion. You can also use the `getFeedVersions` API call (http://transitfeeds.com/api/swagger/#!/default/getFeedVersions) to determine this programmatically.

**Comment by HendX** [comment]
(the start/finish date are included in the response, so you can retrieve all the latest versions and figure out the current one)
