### ISSUE TITLE
STM (Montreal, ID 39) URL changed

### ISSUE THREAD

**Issue by gboudreau** [OpenMobilityData/OpenMobilityData-Public#26]
http://transitfeeds.com/p/societe-de-transport-de-montreal/39

They changed the feed's URL to:
http://www.stm.info/sites/default/files/gtfs/gtfs_stm150330.zip

Ref:
http://www.stm.info/en/about/developers

No idea why they started changing URLs with each release... Does transitfeeds somehow support those kind of "moving" GTFS URLs..? Maybe using a scraper or something?

**Comment by HendX** [comment]
Thanks - updated now.

The site can support changing URLs but I haven't implemented for STM because I couldn't reliably predict how it will be named each time - bit of a nuisance!

I'm planning on adding better internal reporting so I'll know when a feed is about to expire, that's on my todo list.

**Comment by gboudreau** [comment]
Next dataset: http://www.stm.info/sites/default/files/gtfs/gtfs_stm150504.zip

**Comment by HendX** [comment]
Thanks - Updated. Although it appears this file is identical to the previous version.

**Comment by gboudreau** [comment]
Next data set, Aug 31+:
http://www.stm.info/sites/default/files/gtfs/gtfs_stm-150831.zip

**Comment by HendX** [comment]
@gboudreau Thanks - do you know if they will republish to the gtfs_stm.zip file? I'd rather keep the URL static and have it pick up the new one automatically

**Comment by gboudreau** [comment]
Me too! No idea what is their plan, but Aug. 31 should complete their migration to their new version of their GTFS; they were keeping two versions, and will stop that then. Hopefully, that means they will start publishing on the same URL again.

**Comment by HendX** [comment]
Thanks - I think I will leave it for now and hope it pulls in the new URL when they put it on the current URL

**Comment by gboudreau** [comment]
Looks like the gtfs_stm.zip URL is now pointing to the Aug.31+ data.
Hopefully, next time they publish an updated GTFS, they re-use that URL.
