### ISSUE TITLE
Calgary Transit GTFS-Realtime Feeds

### ISSUE THREAD

**Issue by kencon** [OpenMobilityData/OpenMobilityData-Public#273]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: **Canada**

- [x] REGION: **Alberta**

- [x] CITY: **Calgary**

- [x] DIRECT DOWNLOAD URL: 
&nbsp;&nbsp;&nbsp;&nbsp; **Vehicle Positions:** http://transitdata.calgary.ca/ctransit/vehiclepositions.pb
&nbsp;&nbsp;&nbsp;&nbsp; **Trip Updates:** http://transitdata.calgary.ca/ctransit/tripupdates.pb
&nbsp;&nbsp;&nbsp;&nbsp; **Service Alerts:** http://transitdata.calgary.ca/ctransit/alerts.pb
  
- [x] FEED ACCESS INFO: https://data.calgary.ca/browse?q=calgary%20transit&sortBy=relevance&utf8=%E2%9C%93

- [x] This feed is reliably updated: **YES**

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions): **YES**

**Comment by HendX** [comment]
These URLs give me a 404 (or sometimes a 403). I tried registering for the feeds in case they need my static IP, but it still doesn't work.

Do these still work for you @kencon?

**Comment by kencon** [comment]
I'm receiving a 404 error as well so they must've changed something with their feeds probably to restrict access unless you have an API key I assume.
