### ISSUE TITLE
Insert BUS data from Rio de Janeiro

### ISSUE THREAD

**Issue by drcrescencio** [OpenMobilityData/OpenMobilityData-Public#277]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: BRAZIL

- [ ] REGION: RIO DE JANEIRO

- [ ] CITY: RIO DE JANEIRO

- [ ] DIRECT DOWNLOAD URL: http://dadosabertos2.rio.rj.gov.br/dadoaberto/google-transit/google_transit.zip
  
- [ ] FEED ACCESS INFO: http://data.rio/dataset/onibus-gtfs/resource/2de80207-ae46-4955-8adb-9eee0c89febb

- [ ] This feed is reliably updated
Jan 29, 2016

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)
Oficial feed from town hall

**Comment by HendX** [comment]
This doesn't appear to be reliably updated, as the data is out of date.
