### ISSUE TITLE
Brisbane Translink real-time data feed page  is showing an error again

### ISSUE THREAD

**Issue by lydiahoang** [OpenMobilityData/OpenMobilityData-Public#280]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: ____Australia__________________

- [ ] REGION: ______Brisbane________________

- [ ] CITY: ________Brisbane______________

- [ ] DIRECT DOWNLOAD URL: https://
  http://transitfeeds.com/p/translink/74
![http error 500](https://user-images.githubusercontent.com/26017943/29111469-b55c6e00-7d2d-11e7-8bf8-82d3385841b2.PNG)

  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by lydiahoang** [comment]
Hi,  could it be that the code hasn't taken into account the number of rows needed to display the data info?  is that why this error keeps appearing before 7am and after 5pm?  Kind Regards, Lydia

**Comment by HendX** [comment]
It's to do with the amount of server resources required at those times if day as there are more buses on the road then and therefore more data.

May I ask how you're using the data that you've noticed this pattern?

**Comment by lydiahoang** [comment]
Hi Quentin,
I'm doing an assignment where I need to download 2 days' worth of real time data (one weekday and one weekend).  This is how I keep running into the error messages.  Do you think it's possible at all to correct the error?
Kind Regards,Lydia

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Quentin Zervaas <notifications@github.com> Date: 9/08/2017  9:23 PM  (GMT+10:00) To: TransitFeeds/TransitFeeds-Public <TransitFeeds-Public@noreply.github.com> Cc: Lydia Hoang <lydia.hoang@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [TransitFeeds/TransitFeeds-Public] Brisbane Translink real-time data feed page is showing an error again (#280) 
It's to do with the amount of server resources required at those times if day as there are more buses on the road then and therefore more data.
May I ask how you're using the data that you've noticed this pattern?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TransitFeeds/TransitFeeds-Public","title":"TransitFeeds/TransitFeeds-Public","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TransitFeeds/TransitFeeds-Public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HendX in #280: It's to do with the amount of server resources required at those times if day as there are more buses on the road then and therefore more data.\r\n\r\nMay I ask how you're using the data that you've noticed this pattern?"}],"action":{"name":"View Issue","url":"https://github.com/TransitFeeds/TransitFeeds-Public/issues/280#issuecomment-321227389"}}}

**Comment by HendX** [comment]
Note that the data that I publish is only updated hourly, where as Translink update it every 30 seconds or so.

I want to fix it obviously, but it's not straightforward for me to quickly do.

Can you instead try accessing this URL and see if it works?

http://transitfeeds.com/p/translink/74/source

Alternatively, you could pull straight from their protocol buffer file and process it yourself.

**Comment by lydiahoang** [comment]
Hi Quentin,
Hourly definitely works for me :)
Kind Regards,Lydia


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Quentin Zervaas <notifications@github.com> Date: 10/08/2017  11:59 AM  (GMT+10:00) To: TransitFeeds/TransitFeeds-Public <TransitFeeds-Public@noreply.github.com> Cc: Lydia Hoang <lydia.hoang@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [TransitFeeds/TransitFeeds-Public] Brisbane Translink real-time data feed page is showing an error again (#280) 
Note that the data that I publish is only updated hourly, where as Translink update it every 30 seconds or so.
I want to fix it obviously, but it's not straightforward for me to quickly do.
Can you instead try accessing this URL and see if it works?
http://transitfeeds.com/p/translink/74/source
Alternatively, you could pull straight from their protocol buffer file and process it yourself.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TransitFeeds/TransitFeeds-Public","title":"TransitFeeds/TransitFeeds-Public","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TransitFeeds/TransitFeeds-Public"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HendX in #280: Note that the data that I publish is only updated hourly, where as Translink update it every 30 seconds or so.\r\n\r\nI want to fix it obviously, but it's not straightforward for me to quickly do.\r\n\r\nCan you instead try accessing this URL and see if it works?\r\n\r\nhttp://transitfeeds.com/p/translink/74/source\r\n\r\nAlternatively, you could pull straight from their protocol buffer file and process it yourself."}],"action":{"name":"View Issue","url":"https://github.com/TransitFeeds/TransitFeeds-Public/issues/280#issuecomment-321429271"}}}
