### ISSUE TITLE
STIF feed URL changed (is currently not updated for a month on transitfeeds consequently)

### ISSUE THREAD

**Issue by kalon33** [OpenMobilityData/OpenMobilityData-Public#290]
STIF GTFS feed (mirrored at http://transitfeeds.com/p/stif/822) is now split in two versions: 

[v1](https://opendata.stif.info/explore/dataset/offre-horaires-tc-gtfs-idf/files/1358060685e64b78995f7a217bb169e8/download/) which is identical to the previous one

[v2](https://opendata.stif.info/explore/dataset/offre-horaires-tc-gtfs-idf/files/73abe383c9dd51e1d78be6e672a2da3a/download/) which has proper destinations and accessibility information (and should also has fare zones according to upstream, but no fares yet)

- [x] COUNTRY: FRANCE

- [x] REGION: Ile de France

- [x] CITY: Paris

- [x] DIRECT DOWNLOAD URL: see above
  
- [x] FEED ACCESS INFO: https://opendata.stif.info/page/licences/
- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by stevevance** [comment]
The feed that Transitland is [currently using](https://opendata.stif.info/explore/dataset/offre-horaires-tc-gtfs-idf/files/f24cf9dbf6f80c28b8edfdd99ea16aad/download/) (which seems to have expired this summer) has a different set of agencies than the **v2** feed above. 

Transitland would lose:
- CARS PERRON
- Transdev Ile-de-France Houdan

Transitland would gain:
- Service Urbain de Villecresnes
- Houdanais (this might be the same as Transdev Ile-de-France Houdan)

**Comment by kalon33** [comment]
It has changed again and moved as a [v3](https://data.iledefrance-mobilites.fr/explore/dataset/offre-horaires-tc-gtfs-idf/files/736ca2f956a1b6cc102649ed6fd56d45/download/) to a new website. Please fix again @tylerdillard :)

**Comment by tylerdillard** [comment]
@kalon33 Thank you Nicolas. Updated on OMD.
