### ISSUE TITLE
Austrlalia NSW TDX site is no more

### ISSUE THREAD

**Issue by jayenashar** [OpenMobilityData/OpenMobilityData-Public#301]
https://transitfeeds.com/p/transport-for-nsw/237 points to a dead feed.  feed still exists, but is supposed to be accessed via a login-wall.

- [x] COUNTRY: Australia

- [x] REGION: NSW

- [x] DIRECT DOWNLOAD URL: https://opendata.transport.nsw.gov.au/sites/default/files/resources/full_greater_sydney_gtfs_static_0.zip
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO: https://opendata.transport.nsw.gov.au/dataset/timetables-complete-gtfs
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by stevevance** [comment]
Over at Transitland we are using [this URL](https://opendata.transport.nsw.gov.au/sites/default/files/resources/full_greater_sydney_gtfs_static_0.zip) to get Sydney.

**Comment by jayenashar** [comment]
thanks @stevevance not sure why i didn't see your comment before, but i've just edited my comment

**Comment by canales** [comment]
updated. should be visible tomorrow
