### ISSUE TITLE
Alternative official feed for Australia NSW

### ISSUE THREAD

**Issue by jayenashar** [OpenMobilityData/OpenMobilityData-Public#302]
#301 is the better feed of the two, but this one matches the available GTFS-realtime IDs.

Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: Australia

- [x] REGION: NSW

- [ ] DIRECT DOWNLOAD URL: https://
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO: https://opendata.transport.nsw.gov.au/dataset/public-transport-timetables-realtime
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
The problem with this feed is that it needs quite a bit of custom code to authenticate and download the feeds automatically.
