### ISSUE TITLE
Lithuanian feeds

### ISSUE THREAD

**Issue by HendX** [OpenMobilityData/OpenMobilityData-Public#31]
Would not download at time of trying.

Vilnius, Lithuania:
http://www.stops.lt/vilnius/vilnius/gtfs.zip

Kaunas, Lithuania:
http://www.stops.lt/kaunas/kaunas/gtfs.zip

Klaipėda, Lithuania:
http://www.stops.lt/klaipeda/klaipeda/gtfs.zip

Panevėžys, Lithuania:
http://www.stops.lt/panevezys/panevezys/gtfs.zip

Druskininkai, Lithuania:
http://www.stops.lt/druskininkai/druskininkai/gtfs.zip

**Comment by Gooinski** [comment]
downloads worked on Feb 26th 2016.
The Panevėžys feed seems to be missing agency.txt details.
Thanks for these details.

**Comment by mldickens** [comment]
OK, I added these
http://transitfeeds.com/l/475-lithuania

Looks like they have all been updated in the last couple months.

**Comment by canales** [comment]
All are working and with updated feeds.
