### ISSUE TITLE
Please add Ben Franklin Transit (bft.org)

### ISSUE THREAD

**Issue by benfranklintransit** [OpenMobilityData/OpenMobilityData-Public#311]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [X ] COUNTRY: USA

- [X ] REGION: WA State

- [ X] CITY: Richland

- [X ] DIRECT DOWNLOAD URL: https://www.bft.org/gtfs/google_transit.zip
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: 
  This is a web page with more information about the feed (such as licensing or access instructions)

- [X ] This feed is reliably updated

- [X ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by mldickens** [comment]
I added this feed

http://transitfeeds.com/p/ben-franklin-transit/915
