### ISSUE TITLE
Portugal, Lisboa, Carris (buses)

### ISSUE THREAD

**Issue by adavidzh** [OpenMobilityData/OpenMobilityData-Public#313]
Part of a series of new contents for Lisboa, Portugal: #313, #314, #315, #316, #317, #317, #319, and #320.

- [x] COUNTRY: Portugal

- [x] REGION: Lisboa

- [x] CITY: Lisboa

- [x] DIRECT DOWNLOAD URL: http://www.transporlis.pt/Portals/0/OpenData/gtfs/zip/1/gtfs_1.zip
  
- [x] FEED ACCESS INFO: http://dadosabertos.cm-lisboa.pt/dataset/informacao-sobre-transportes-publicos-da-cidade-de-lisboa-carris

- [x] This feed is reliably updated (every 3 months).

- [x] This is an official feed.

**Comment by canales** [comment]
@adavidzh Do you know where can we get the information for Carris trams (http://www.carris.pt/pt/electricos-articulados/)? Seems like everything in their dataset is classified as buses, but there are trams in Lisbon and I can't seem to find them in any dataset. 

Also, if you have any hint about realtime data, it will be more than welcomed.

**Comment by adavidzh** [comment]
Hi @canales, I'm afraid I don't. I just added what I once found out. I would suggest contacting the manager of these data, <dadosabertos@cm-lisboa.pt>.

**Comment by canales** [comment]
@adavidzh sounds good, thanks.
