### ISSUE TITLE
Ability to submit new data sources directly on site

### ISSUE THREAD

**Issue by HendX** [OpenMobilityData/OpenMobilityData-Public#32]
Currently users need a GitHub account to request new data. Would like to have them fill out a form directly on transitfeeds.com to simplify this process.

It should use a control similar to this to enable the user to nominate the location:

https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

**Comment by caywood** [comment]
We have this now. http://transitfeeds.com/submit
