### ISSUE TITLE
Feature Request: Email Alert for a Feed update

### ISSUE THREAD

**Issue by 3vivekb** [OpenMobilityData/OpenMobilityData-Public#329]
It would be nice if I could get an email alert if a feed i'm interested in gets updated.

Alternatively I imagine I can code something up using the swagger api.

**Comment by aytee17** [comment]
```feed_into.txt``` has the expiry date of the feed. You could check for an update ```GET /getLatestFeedVersion```after the expiry.

**Comment by caywood** [comment]
One solution would be for you to hook up the API above to email using a service like IFTTT. https://ifttt.com/email
