### ISSUE TITLE
Add titsa Tenerife, Canary Islands, Spain

### ISSUE THREAD

**Issue by ubahnverleih** [OpenMobilityData/OpenMobilityData-Public#333]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: Spain

- [x] REGION: Canary Islands

- [x] CITY: Tenerife (complete island)

- [x] DIRECT DOWNLOAD URL: http://www.titsa.com/Google_transit.zip
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO: http://www.tenerifedata.com/dataset/titsa-informacion-sobre-sistema-de-transporte
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by canales** [comment]
Added
