### ISSUE TITLE
RMV, Germany

### ISSUE THREAD

**Issue by Dasmaeht** [OpenMobilityData/OpenMobilityData-Public#334]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: Germany

- [x] REGION: Hessia

- [x] CITY: Frankfurt, Wiesbaden, Mainz, Darmstadt & others

- [x] DIRECT DOWNLOAD URL: https://opendata.rmv.de/site/files/rmv01/RMV_Haltestellen.zip
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO: https://opendata.rmv.de/site/nutzungsbedingungen.html  (License)
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated ?
RMV provides an own API. They were quite afraid of releasing a GTFS-file because they wanted to be sure that only reliable data is published; so reliability is rather expectable. 

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by nighthawk** [comment]
Unfortunately, this is not a GTFS feed, it's just a CSV of stops in a custom data format. Anything else is only available through an API 👎

**Comment by stevevance** [comment]
Argh! It would be great if there was GTFS for this region.
