### ISSUE TITLE
Official GTFS for Knoxville, Tennessee

### ISSUE THREAD

**Issue by cbrakewood** [OpenMobilityData/OpenMobilityData-Public#343]
- [ ] COUNTRY: USA

- [ ] REGION: Tennessee

- [ ] CITY: Knoxville

- [ ] DIRECT DOWNLOAD URL: https://
http://www.knoxvilletn.gov/UserFiles/Servers/Server_109478/File/KAT/gtfs-kat.zip
  
- [ ] FEED ACCESS INFO: https://
http://www.knoxvilletn.gov/government/opendata/knoxville_area_transit_kat_gtfs_feed

- [ ] This feed is reliably updated YES

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions) YES

**Comment by mldickens** [comment]
I added this feed

**Comment by mldickens** [comment]
http://transitfeeds.com/p/knoxville-area-transit-kat
