### ISSUE TITLE
Italy, Liguria, Genoa

### ISSUE THREAD

**Issue by traversaro** [OpenMobilityData/OpenMobilityData-Public#344]
- [x] COUNTRY: Italy
- [x] REGION: Liguria
- [x] CITY: Genoa
- [x] DIRECT DOWNLOAD URL: https://www.amt.genova.it/amt/GTFS/GTFS_AMT_GENOVA.zip
- [x] FEED ACCESS INFO: https://www.amt.genova.it/amt/amministrazione-trasparente/open-data/
- [x] This feed is reliably updated
- [x] This is an official feed

**Comment by stebazzi** [comment]
Any idea about when it will be added?

**Comment by canales** [comment]
@stebazzi  Added, you should see it now, https://transitfeeds.com/p/amt-genova/1011

**Comment by traversaro** [comment]
Thanks a lot!
