### ISSUE TITLE
Update Marche GTFS

### ISSUE THREAD

**Issue by gafrigio** [OpenMobilityData/OpenMobilityData-Public#354]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [X] COUNTRY: Italy

- [X] REGION: Marche

- [ ] CITY: ______________________

- [X] DIRECT DOWNLOAD URL: http://www.trasporti.marche.it/downloads/opendata/GTFS_TRASPORTI_UNIFICATO_MarcheItaly.zip 
  This is the URL of the GTFS zip
  
- [X] FEED ACCESS INFO: http://www.trasporti.marche.it/Downloads/opendata/
  This is a web page with more information about the feed (such as licensing or access instructions)

- [X] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by canales** [comment]
@gafrigio seems like the GTFS url, delivers an outdated feed with calendar dates ending in 2018. Is there another url that we could use that provides the latest feed?
