### ISSUE TITLE
Update LADOT feed

### ISSUE THREAD

**Issue by acnetj** [OpenMobilityData/OpenMobilityData-Public#355]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [x] COUNTRY: _USA_

- [x] REGION: _______________California_______

- [x] CITY: __Los Angeles___

- [x] DIRECT DOWNLOAD URL: http://lacitydot.com/gtfs/administrator/gtfszip/ladotgtfs.zip
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO: https://www.ladottransit.com/dla.html
  This is a web page with more information about the feed (such as licensing or access instructions)

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by mldickens** [comment]
I updated this feed.
