### ISSUE TITLE
OVapi trip updates

### ISSUE THREAD

**Issue by sclmarijt** [OpenMobilityData/OpenMobilityData-Public#356]
Hi,

Under the feeds located http://transitfeeds.com/p/ov the feed OVapi trip updates is mentioned but not reachable. In the past it was mentioned that server capacity in combination with the amount of data associated with OVapi related sourches was a problem, but I am not aware whether this a still the actual issue or not.

With kind regards,

Sander

**Comment by canales** [comment]
@sclmarijt It should be attainable through the Official download URL exposed. Let me know if it's not possible from your side.
