### ISSUE TITLE
Poland > Poznań

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#358]
Another Polish agency has shared their GTFS feed: ZTM Poznań - the organiser of public transportation in Poznań and neighbouring municipalities.

- [x] COUNTRY: Poland

- [x] CITY: Poznań

- [x] DIRECT DOWNLOAD URL: http://ztm.poznan.pl/pl/dla-deweloperow/getGTFSFile
  
- [x] FEED ACCESS INFO: http://ztm.poznan.pl/pl/dla-deweloperow/index

- [x] This feed is reliably updated

- [x] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by canales** [comment]
Done
