### ISSUE TITLE
In the opening feed window summary, please identify which feeds are GTFS-RT with icon. Thanks

### ISSUE THREAD

**Issue by denby211** [OpenMobilityData/OpenMobilityData-Public#361]
Please complete the following checklist when submitting a new data feed.

If you have multiple feeds to submit, please create a separate issue for each of them.

- [ ] COUNTRY: ______________________

- [ ] REGION: ______________________

- [ ] CITY: ______________________

- [ ] DIRECT DOWNLOAD URL: https://
  This is the URL of the GTFS zip
  
- [ ] FEED ACCESS INFO: https://
  This is a web page with more information about the feed (such as licensing or access instructions)

- [ ] This feed is reliably updated

- [ ] This is an official feed (we try not to include unofficial feeds, but may make exceptions)

**Comment by HendX** [comment]
Can you give me an example URL of where you want to see this? Feeds are already tagged with GTFS or GTFS-realtime

**Comment by denby211** [comment]
Hi Quentin – thank you for getting back with me.



Two things – first I’d like to see the tag line GTFS RealTime with the
provider. Second to look for providers by state I’d like it to be abit
easier so to sort providers by State.



I use your excellent site to support transit systems specifically for
digital bus stop arrivals.





Here ‘s the second request.









*From:* Quentin Zervaas [mailto:notifications@github.com]
*Sent:* Thursday, February 8, 2018 4:31 PM
*To:* TransitFeeds/TransitFeeds-Public <
TransitFeeds-Public@noreply.github.com>
*Cc:* denby211 <smarks@chkamerica.com>; Author <author@noreply.github.com>
*Subject:* Re: [TransitFeeds/TransitFeeds-Public] In the opening feed
window summary, please identify which feeds are GTFS-RT with icon. Thanks
(#361)



Can you give me an example URL of where you want to see this? Feeds are
already tagged with GTFS or GTFS-realtime

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TransitFeeds/TransitFeeds-Public/issues/361#issuecomment-364270950>,
or mute the thread

**Comment by caywood** [comment]
Thanks for the suggestion, but OpenMobilityData isn't really designed to support business development. It's currently pretty easy to see GTFS-Realtime tag by going into a provider, for example, http://transitfeeds.com/p/mta. Or you can use the API to search for realtime feeds.
