### ISSUE TITLE
Venice ACTV data not updated: 7 days since update released on publisher site

### ISSUE THREAD

**Issue by lubbo** [OpenMobilityData/OpenMobilityData-Public#366]
ACTV navigazione FEED available at:
http://actv.avmspa.it/sites/default/files/attachments/opendata/navigazione/actv_nav.zip
was updated on 21-Mar-2018 22:30

Today 29-Mar-2018 the feed update is not available on TransitFeed.

**Comment by stebazzi** [comment]
It's working well

**Comment by lubbo** [comment]
Maybe now... 12 months later... I’m now using another way.
