### ISSUE TITLE
Poland > Warsaw > SKM: Oboslete

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#380]
Data from [SKM Feed](http://transitfeeds.com/p/szybka-kolej-miejska-w-warszawie/790) is now included in [ZTM Feed](http://transitfeeds.com/p/ztm-warszawa/720).

This makes the SKM feed obsolete and means that it should be removed.

- [x] URL ON TRANSITFEEDS: http://transitfeeds.com/p/szybka-kolej-miejska-w-warszawie/790
- [x] NEW DOWNLOAD URL (direct link): :x:

**Comment by canales** [comment]
Waiting for #394 to be completed

**Comment by tylerdillard** [comment]
Deprecated.

**Comment by MKuranowski** [comment]
Sorry, but the feed is not marked as deprecated <http://transitfeeds.com/l/518-warsaw-poland>.

What's weird, the data inside <http://transitfeeds.com/p/szybka-kolej-miejska-w-warszawie/790/latest/agencies> is from a different agency, from a different city ([PKP SKM Trójmiasto](http://transitfeeds.com/p/pkp-szybka-kolej-miejska-w-trojmie-cie) to be exact)).

And what's more, [PKP SKM Trójmiasto](http://transitfeeds.com/p/pkp-szybka-kolej-miejska-w-trojmie-cie) is marked as deprecated, whereas the datasource is still valid (<https://przyjazdy.pl/latest/skmt.zip>).
