### ISSUE TITLE
Poland > Warsaw > Metro Warszawskie: Obsolete

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#381]
Data from [Metro Warszawskie feed](http://transitfeeds.com/p/metro-warszawskie/721) is now included in [ZTM Feed](http://transitfeeds.com/p/ztm-warszawa/720).

This makes the Metro feed obsolete and means that it should be removed.

- [x] URL ON TRANSITFEEDS: http://transitfeeds.com/p/metro-warszawskie/721
- [x] NEW DOWNLOAD URL (direct link): :x:

**Comment by canales** [comment]
For deprecation. Waiting for issue #394 to be completed
