### ISSUE TITLE
Poland > Warsaw > KMŁ: New feed info website

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#387]
## UPDATE EXISTING FEED:

- [x] URL ON TRANSITFEEDS: http://transitfeeds.com/p/komunikacja-miejska-omianki/723
- [x] NEW DOWNLOAD URL (direct link): :heavy_minus_sign: _unchanged_
- [x] NEW FEED INFORMATION URL: https://mkuran.pl/feed/

**Comment by canales** [comment]
Done
