### ISSUE TITLE
TEC GTFS new url

### ISSUE THREAD

**Issue by stebazzi** [OpenMobilityData/OpenMobilityData-Public#393]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL ON TRANSITFEEDS: https://transitfeeds.com/p/societe-regionale-wallonne-du-transport/529
- [x] NEW DOWNLOAD URL (direct link): http://opendata.tec-wl.be/Current%20GTFS/TEC-GTFS.zip

**Comment by mldickens** [comment]
I've updated this one.

**Comment by canales** [comment]
@mldickens thanks
