### ISSUE TITLE
GTFS Regional Sweden

### ISSUE THREAD

**Issue by gtfs0** [OpenMobilityData/OpenMobilityData-Public#401]
There are regional GTFS feeds for a few regions in Sweden. These are more detailed than the nationwide GTFS feed.

https://www.trafiklab.se/node/17865/documentation

API key must be created at https://www.trafiklab.se/api-nycklar
You can log in with your existing Trafiklab account but you have to create a separate API key for this feeds.

**Comment by canales** [comment]
@gtfs0 Added. Protobuf files for the realtime data seems to be corrupt, which is why they can't be displayed.

**Comment by gtfs0** [comment]
It seems like only the SL feeds has been added. There are other feeds too:
UL https://gtfs-pp.samtrafiken.se/ul/ul.zip?key= <API key>
Östgötatrafiken https://gtfs-pp.samtrafiken.se/otraf/otraf.zip?key= <API key>
Västtrafik https://gtfs-pp.samtrafiken.se/vt/vt.zip?key= <API key>
Skånetrafiken https://gtfs-pp.samtrafiken.se/skane/skane.zip?key= <API key>
KLT https://gtfs-pp.samtrafiken.se/klt/klt.zip?key= <API key>
X-trafik https://gtfs-pp.samtrafiken.se/xt/xt.zip?key= <API key>
Dalatrafik https://gtfs-pp.samtrafiken.se/dt/dt.zip?key= <API key>

Use the same key as for the SL feed.
