### ISSUE TITLE
VBB GTFS - URL Changed

### ISSUE THREAD

**Issue by gtfs0** [OpenMobilityData/OpenMobilityData-Public#408]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL ON TRANSITFEEDS: http://transitfeeds.com/p/verkehrsverbund-berlin-brandenburg/213
- [x] NEW DOWNLOAD URL (direct link): https://www.vbb.de/media/download/2029

If application:

- [x] NEW FEED INFORMATION URL: https://www.vbb.de/unsere-themen/vbbdigital/api-entwicklerinfos/datensaetze

**Comment by leonardehrenfried** [comment]
Could you guys please take a look at this issue?

**Comment by canales** [comment]
Yes, just updated
