### ISSUE TITLE
Canada VIA Rail GTFS

### ISSUE THREAD

**Issue by olivierhill** [OpenMobilityData/OpenMobilityData-Public#409]
- [x] COUNTRY: Canada

- [x] CITY: All

- [x]  DIRECT DOWNLOAD URL: 
https://www.viarail.ca/sites/all/files/gtfs/viarail.zip

- [x]  FEED ACCESS INFO: https://www.viarail.ca/en/developer-resources

- [x]  This feed is reliably updated

- [x]  This is an official feed (we try not to include unofficial feeds, but may make exceptions) - YES

**Comment by canales** [comment]
Added
