### ISSUE TITLE
Add Hong Kong feed

### ISSUE THREAD

**Issue by calvintam236** [OpenMobilityData/OpenMobilityData-Public#41]
As Hong Kong is one of the city that heavily depends on public transit, there are many agencies (bus, railway, ferry, etc.) Please add the feed.

https://en.wikipedia.org/wiki/Transport_in_Hong_Kong

**Comment by HendX** [comment]
Hi Calvin - I'd love to, but I don't have access to their data feeds (such as a GTFS feed). If you know how to access it, please let me know!

**Comment by calvintam236** [comment]
Actually they should have GTFS data as Google Maps are using. Might need to contact them in order to grant access.

Ref. https://maps.google.com/landing/transit/cities/

**Comment by HendX** [comment]
Thanks - at this stage due my limited resources, I'll need them to make their data publicly available via an accessible URL. I'll leave this issue open for now though.

**Comment by c933103** [comment]
GTFS data for Hong Kong expected to be available in second half of this year:
http://www.info.gov.hk/gia/general/201712/13/P2017121300423p.htm

**Comment by canales** [comment]
@c933103 If you have any update on the announcement above, that'd be great. I haven't yet seen any public feed for Hong Kong
