### ISSUE TITLE
Realtime Feeds in BC

### ISSUE THREAD

**Issue by useless2764** [OpenMobilityData/OpenMobilityData-Public#410]
Comox Valley
Alerts: https://comox.mapstrat.com/current/gtfrealtime_ServiceAlerts.bin
Trip Updates: https://comox.mapstrat.com/current/gtfrealtime_TripUpdates.bin
Vehicle Locations: https://comox.mapstrat.com/current/gtfrealtime_VehiclePositions.bin

Kamloops
Alerts: https://kamloops.mapstrat.com/current/gtfrealtime_ServiceAlerts.bin
Trip Updates: https://kamloops.mapstrat.com/current/gtfrealtime_TripUpdates.bin
Vehicle Locations: https://kamloops.mapstrat.com/current/gtfrealtime_VehiclePositions.bin

Kelowna
Alerts: https://kelowna.mapstrat.com/current/gtfrealtime_ServiceAlerts.bin
Trip Updates: https://kelowna.mapstrat.com/current/gtfrealtime_TripUpdates.bin
Vehicle Locations: https://kelowna.mapstrat.com/current/gtfrealtime_VehiclePositions.bin

Nanaimo
Alerts: https://nanaimo.mapstrat.com/current/gtfrealtime_ServiceAlerts.bin
Trip Updates: https://nanaimo.mapstrat.com/current/gtfrealtime_TripUpdates.bin
Vehicle Locations: https://nanaimo.mapstrat.com/current/gtfrealtime_VehiclePositions.bin

Squamish: https://squamish.mapstrat.com/current/
Whistler: https://whistler.mapstrat.com/current/

**Comment by canales** [comment]
Done
