### ISSUE TITLE
GTFS URL update - BWI Airport Shuttles

### ISSUE THREAD

**Issue by colemccarren** [OpenMobilityData/OpenMobilityData-Public#413]
## UPDATE EXISTING FEED:

- [ ] URL on OpenMobilityData: http://transitfeeds.com/p/bwi-airport-shuttle

- [ ] New download URL (direct link): https://github.com/mobilityequity/maryland-local-gtfs/raw/master/BWI_GTFS.zip

- [ ] Update Feed Info / Terms of Use link: https://github.com/mobilityequity/maryland-local-gtfs

**Comment by canales** [comment]
Done
