### ISSUE TITLE
GTFS URL update - Ocean City Transportation

### ISSUE THREAD

**Issue by colemccarren** [OpenMobilityData/OpenMobilityData-Public#418]
## UPDATE EXISTING FEED:

- [ ] URL on OpenMobilityData: http://transitfeeds.com/p/ocean-city-transportation

- [ ] New download URL (direct link): https://github.com/mobilityequity/maryland-local-gtfs/raw/master/OC_GTFS.zip

- [ ] Update Feed Info / Terms of Use link: https://github.com/mobilityequity/maryland-local-gtfs

**Comment by canales** [comment]
Done
