### ISSUE TITLE
Clarify "Location" on the Submit page

### ISSUE THREAD

**Issue by mcplanner** [OpenMobilityData/OpenMobilityData-Public#422]
It's unclear what is meant by "Location" on the /submit page. Is that a URL, city, or agency? I can't get any of those to validate. I suggest clearer language.

**Comment by caywood** [comment]
The http://transitfeeds.com/submit page seems to be broken right now in that location search isn't working, locations we know should be in the database like "Austria" are not coming up. 

@ethanpooley can you check if this is a regression from our release?

**Comment by ethanpooley** [comment]
@mcplanner It should be a geographic or political region of any specificity: nation, state/province, city, etc.

Location creation is working again. Navigate to the most specific location that already exists, then search for the common name of the next-most-specific location you wish to use. For example: `North America` > `US` > `California` > (search for "Turlock")

That should result in a search result with options for what kind of entity to create, such as "City":
![screenshot from 2019-02-25 01-48-05](https://user-images.githubusercontent.com/856884/53329384-d1f61900-38a0-11e9-9e8f-9bf1f9794de6.png)

Repeat if necessary to create siblings or locations with more granularity. Just make sure the current location is the one you wish to be the parent of any new location.
