### ISSUE TITLE
Add support for What3Words location data, as an alternative to WGS 84 LatLong coordinates

### ISSUE THREAD

**Issue by ghost** [OpenMobilityData/OpenMobilityData-Public#424]
What3Words divides the entire planet into a grid of 3 m x 3 m, and names each square in the grid with a unique set of three words. It would be ideal for pinpointing bus stops (typically 12 or 18 m x 3 m, or multiples thereof) and drawing routes on maps. Support for it should be added to the General Transit Feed Specification as an alternative to WGS 84 coordinates. Find out more about What3Words at https://what3words.com/.

**Comment by caywood** [comment]
Changes to GTFS are out of scope. Issue reporter has been deleted (for spam?)
