### ISSUE TITLE
Trip Updates/Vehicle Location Feed

### ISSUE THREAD

**Issue by jmiller513** [OpenMobilityData/OpenMobilityData-Public#427]
I have noticed that the Trip Updates/Vehicle Location feed for agencies that provide this information has not been updated in over 6 days when it normally refreshes hourly. The last refresh was February 11th at 2:30. Agencies in my area that have this information is Cincinnati Metro, Transit Authority of Northern Kentucky, and Central Ohio Transit Authority.

**Comment by ethanpooley** [comment]
Thank you for this report @jmiller513. There was indeed a service outage for a while on our end and the system is currently dealing with the backlog from that. It should be fully restored shortly.

**Comment by ethanpooley** [comment]
There we go.

![screenshot from 2019-02-20 08-56-11](https://user-images.githubusercontent.com/856884/53109268-66512c00-34ed-11e9-882d-ca3d3bf1d439.png)
