### ISSUE TITLE
Create update button for the Admin UI

### ISSUE THREAD

**Issue by canales** [OpenMobilityData/OpenMobilityData-Public#428]
Currently there is no way to make the system to update a feed that has been changed/updated (changing/adding a new URL, adding authorization credentials, regex patterns for links, etc.). Once the save button is clicked on a feed, we need to wait between until the system does the daily automatic checkup of all feeds to fetch the new ones.

**Comment by caywood** [comment]
Update: in Admin mode, the Save button on a Feed should trigger a feed update.

For example see below: http://transitfeeds.com/admin/feeds/feed.php?f=763

![screen shot 2019-03-07 at 12 08 28 pm](https://user-images.githubusercontent.com/11506462/53974936-bfb28100-40d1-11e9-820d-856256037fda.png)

Currently, if you save a feed in a new feed submission (like: http://transitfeeds.com/admin/submissions/details.php?id=2), that WILL update the feed within 5 minutes. We just need to do the same for existing feeds.
