### ISSUE TITLE
Update Hungary MVK feed

### ISSUE THREAD

**Issue by KhrustalevaM** [OpenMobilityData/OpenMobilityData-Public#429]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/mvk-zrt/839
- [ ] New download URL (direct link): http://kearney.cdata.hu/gtfs-static/mvkzrt.zip

**Comment by canales** [comment]
Done

**Comment by hoordev** [comment]
New url available: [http://gtfs.cdata.hu/mvkzrt.zip](http://gtfs.cdata.hu/mvkzrt.zip)
