### ISSUE TITLE
Bad acronym for Europe-Germany-Aachener Verkehrs Verbund (should be AVV, not AAV)

### ISSUE THREAD

**Issue by mastacheata** [OpenMobilityData/OpenMobilityData-Public#435]
Is there a technical reason why the Aachener Verkehrsverbund is abbreviated as AAV on the transitfeeds website?
The official acronym is AVV.

**Comment by canales** [comment]
Typo at the time of submission. It's been corrected now

https://transitfeeds.com/p/aachener-verkehrsverbund/836
