### ISSUE TITLE
rtc-southern-nevada RT feed

### ISSUE THREAD

**Issue by TomGoBravo** [OpenMobilityData/OpenMobilityData-Public#437]
Existing provider http://transitfeeds.com/p/rtc-southern-nevada has a GTFS-RT feed that is not on the site. According to https://www.rtcsnv.com/transit/rtc-transit-services/rtc-transit-developer-information/ the RT feed is at http://rtcws.rtcsnv.com/gtfrt/tripUpdates.pb

**Comment by canales** [comment]
updated
