### ISSUE TITLE
transit shapes look out of shape

### ISSUE THREAD

**Issue by acnetj** [OpenMobilityData/OpenMobilityData-Public#438]
Ever since the site has been converted to Mapbox, the route shapes no longer look correct.

Examples:
http://transitfeeds.com/p/ladot-transit-services/303/latest/trip/29337

The shape does not follow the route pattern.

Many looks like dots are connected at random:
http://transitfeeds.com/p/samtrans/144/latest/route/398-168

The same shape appears normal with Mobility Explorer:
https://mobility-explorer.interline.io/#/routes?bbox=-122.48537063598634%2C37.65025725411621%2C-122.25465774536133%2C37.77749907004604&onestop_id=r-9q9j-398

The shapes are included with many of the GTFS feeds produced by the transit agencies. They appeared normal with the Google Maps formerly used by this site.

Andy

**Comment by caywood** [comment]
@acnetj we're looking into fixing this with Mapbox. Unfortunately, we had to switch off Google Maps due to last year's exorbitant price increases.

**Comment by acnetj** [comment]
I don't blame you for switching from Google. I did too to Leaflet + HERE. I guess the old function of parsing the shapes.txt has been replaced with something else.

**Comment by caywood** [comment]
Another example. https://transitfeeds.com/p/sbb-cff-ffs/793/latest/trip/3366.TA.9-15-j19-1.10.H

**Comment by ciolt** [comment]
Any update on this @caywood? Still broken https://transitfeeds.com/p/south-florida-regional-transportation-authority/699/latest/route/SB

**Comment by stephenyeargin** [comment]
I wrote [a tool](https://wego.yearg.in) for viewing our schedule data using Leaflet ([source code](https://github.com/stephenyeargin/wego-bus-map/blob/master/public/assets/javascript/app.js)). Clicking on a bus (when they are in service) shows where that vehicle is headed. One thing I opted to do was split the rendering of the stop markers from that of the shape itself.
