### ISSUE TITLE
Add feeds for Brazil

### ISSUE THREAD

**Issue by grote** [OpenMobilityData/OpenMobilityData-Public#44]
Hey, you don't have nothing in Latin America.

Here's a GTFS feed for Sao Paulo: 

```
http://www.sptrans.com.br/desenvolvedores/GTFS.aspx 
```

 and Porto Allegre: 

```
http://dados.portoalegre.rs.gov.br/dataset/gtfs 
```

**Comment by HendX** [comment]
Thanks! I've registered for the first one, but they have a pretty annoying login section in front of the data, so I can't easily add this without a ton of work.

Here's the Porto Allegre feed:
http://transitfeeds.com/p/empresa-publica-de-transportes-e-circulacao

**Comment by grote** [comment]
Thanks for adding the one already. I guess you crawl the feeds automatically and have no capabilities at the moment to get feeds behind a login, right?

**Comment by HendX** [comment]
It is possible for me to load feeds from behind a login, but each one typically needs a custom implementation as they all differ. This one especially looks a bit more complex than the other ones I've dealt with.

**Comment by mauricioc-cc** [comment]
Here is the GTFS from Belo Horizonte, Brazil: http://servicosbhtrans.pbh.gov.br/transitfiles/gtfs_bhtransit.zip

**Comment by mldickens** [comment]
Added the Belo Horizonte feed.

http://transitfeeds.com/p/bhtrans/640

**Comment by pauloaug** [comment]
Please add Rio GTFS: http://dadosabertos2.rio.rj.gov.br/dadoaberto/google-transit/google_transit.zip
Thanks!

**Comment by caiorg** [comment]
I've attached a GTFS for São Paulo
[caiorg-636055552204539618.zip](https://github.com/TransitFeeds/TransitFeeds-Public/files/398389/caiorg-636055552204539618.zip)

I've gone through all the process of creating an account and downloading the file and I'm not sure if there's an expiration date, since I'm new to GTFS.

**Comment by rodrigowindows** [comment]
Please add Bage - Rio Grande do Sul GTFS: https://github.com/rodrigowindows/GTFS/blob/master/GTFS_Bage.zip
Thanks

**Comment by canales** [comment]
@pauloaug  do you know where to get an updated feed for Rio? I know Fetranspor is who generates and bundles the feed for all the modes, so if you could ask them that'd be perfect.
