### ISSUE TITLE
Latest VTA feed is broken

### ISSUE THREAD

**Issue by bijanmmarkes** [OpenMobilityData/OpenMobilityData-Public#440]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://transitfeeds.com/p/vta/45 which is currently pulling from http://www.vta.org/getting-around/gtfs-info/data-file -- but it doesn't seem to have pulled the latest perhaps becauase it isn't a direct think although it used to work in the past.

- [ ] New download URL (direct link): http://www.vta.org/sfc/servlet.shepherd/document/download/069A0000001NUea

It seems transitfeeds is still using our expired feed causing downstream applications to break, can you please update our feed to use the direct link from our agency above at vta.org.

Thank you.

**Comment by canales** [comment]
@bijanmmarkes I'll make the update in the link. Just want to make sure that it is not a dynamic URL (having to change every-time there is a new feed), because we can only accept static URLs at the time.

**Comment by bijanmmarkes** [comment]
Thank you so much @canales, The link is static and is where a lot of our systems pull the feed from. It hasn't changed in years.

Kind Regards,

Bijan.

**Comment by canales** [comment]
@bijanmmarkes perfect. I just updated it. In a couple hours you should see the feed updated (the looping of all urls in the system is timed).

**Comment by bijanmmarkes** [comment]
Hey, @canales it seems that transit feeds still hasn't updated even though the new link has been provided.

Still using expired feed as latest: http://transitfeeds.com/p/vta/45/latest

Please advise.

**Comment by canales** [comment]
@ethanpooley I saw this feed got its last update on March 25th. Something must have gotten it stuck. Can you check?

**Comment by bijanmmarkes** [comment]
Any news on this? @ethanpooley @canales

**Comment by ethanpooley** [comment]
@canales I believe the driver method needed to be changed from `findlink` to `direct` now that we have a direct URL. You don't seem to have access to that in the Admin controls, so I changed it myself in the database. If this fixes the issue we'll want to expose that and add some text explaining when to use it.

**Comment by bijanmmarkes** [comment]
Hey @ethanpooley thanks for checking on this. Looks like this still didn't solve the issue though. The latest feed is still pointing to our expired GTFS.

**Comment by ethanpooley** [comment]
There we go. I had to manually ask it to update earlier than it would have, but it did and looks (to me) to be correct: http://transitfeeds.com/p/vta/45

**Comment by canales** [comment]
Thanks @ethanpooley. I saw that it has updated with the latest feed. Closing this one.
