### ISSUE TITLE
MBTA realtime reported as old when it is current

### ISSUE THREAD

**Issue by TomGoBravo** [OpenMobilityData/OpenMobilityData-Public#444]
## UPDATE EXISTING FEED:

- URL on OpenMobilityData: http://transitfeeds.com/p/mbta/92
(and others at http://transitfeeds.com/p/mbta)
are listed as "Below is a snapshot of this feed from 2 July 2018 7:26 AM (42w 5d ago)" but I  fetched https://cdn.mbta.com/realtime/VehiclePositions.pb and the timestamps are from a few minutes ago.

**Comment by caywood** [comment]
We believe we have finally fixed this recurring issue in https://github.com/OpenMobilityData/OpenMobilityData-Public/issues/454#event-2720801906
