### ISSUE TITLE
Unsupported route_sort_order

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#445]
The website shows that `route_sort_order` is an [unrecognized column](http://transitfeeds.com/p/ztm-warszawa/720/latest/file/routes.txt), even though it's [part of the GTFS specification](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#routestxt).

This also means that routes should be showed in the `route_sort_order`-provided order, which they aren't.
![ignored_route_sort_order](https://user-images.githubusercontent.com/16469272/57369959-3f6ed180-718f-11e9-9352-2f59b24ec2dd.png)
(↑ the order of tram routes according to route_sort_order would be 1, 2, 3, 4, …, 10, 11, …; not ~1, 10, 11, …, 2 ,20, …~, as sorting by route_short_name strings would suggest)

**Comment by Cristhian-HA** [comment]
Hello, Thank you for your message, there will be a new version of the site very soon.
