### ISSUE TITLE
GTFS URL update - RTA

### ISSUE THREAD

**Issue by colemccarren** [OpenMobilityData/OpenMobilityData-Public#447]
## UPDATE EXISTING FEED:

- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/regional-transportation-agency-of-central-maryland

- [ ] New download URL (direct link): http://www.transitrta.com/media/gtfs.zip

If application:

- [ ] Update Feed Info / Terms of Use link: http://www.transitrta.com/developer-resources/

**Comment by canales** [comment]
Done, should see it tomorrow updated.
