### ISSUE TITLE
stops map only shows one stop for MBTA

### ISSUE THREAD

**Issue by DamianJBurgos** [OpenMobilityData/OpenMobilityData-Public#449]
Hello,

The stops.txt file is only loading the first bus stop from the file and not the others, this has worked fine in the past. This is for the MBTA GTFS.

https://transitfeeds.com/p/mbta/64/latest/file/stops.txt

**Comment by caywood** [comment]
I didn't understand this issue because the link above shows the stops extract as expected, and "view file" shows all stops.txt. 

The actual issue appears to be that https://transitfeeds.com/p/mbta/64/latest/stops map is only showing one stop on the map.

**Comment by blackmad** [comment]
I also noticed that the validation errors on transitfeeds doesn't show some of the serious errors that the google feedvalidator does (which is that a bunch of the stops are missing stop_lat/stop_lon

![image](https://user-images.githubusercontent.com/445616/71482677-e1503680-27d1-11ea-8d93-2ddd8046d233.png)

**Comment by DamianJBurgos** [comment]
Why was this closed if the issue isn't fixed?

**Comment by Cristhian-HA** [comment]
Apologies, I should have mentioned that unfortunately at this moment we do not have the resources to process this request and we will not be working on this. Please take note that we are currently working on a new version of the site.
Have a great day!
