### ISSUE TITLE
Transport for NSW feed outdated

### ISSUE THREAD

**Issue by ljnicol** [OpenMobilityData/OpenMobilityData-Public#451]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL on OpenMobilityData: http://transitfeeds.com/p/transport-for-nsw/237
- [x] New download URL (direct link): https://opendata.transport.nsw.gov.au/api/download/9ca31d18-5efa-43ec-870d-258ee3388614

If application:

- [ ] New feed information URL: _________________________

**Comment by fabrice-v** [comment]
The URL provided requires authentication (http code 401). We may be able to support it with the right credential sent at support@openmobilitydata.org, referring this issue.
