### ISSUE TITLE
No recent updates to TransLink Vancouver

### ISSUE THREAD

**Issue by ShawnFinnie** [OpenMobilityData/OpenMobilityData-Public#452]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/translink-vancouver/29
- [ ] New download URL (direct link): https://developer.translink.ca/ServicesGtfs/GtfsData

If application:

- [ ] New feed information URL: _________________________

**Comment by ShawnFinnie** [comment]
Hello! It's me again! For GTFS-RT, please find the updated URLs:

Trip Update:       https://gtfs.translink.ca/v2/gtfsrealtime?apikey=[APIKey] 
(Amend on URL -> http://transitfeeds.com/p/translink-vancouver/397)

Position Update: https://gtfs.translink.ca/v2/gtfsposition?apikey=[APIKey]
(Amend on URL -> http://transitfeeds.com/p/translink-vancouver/398)

Service Alerts:     https://gtfs.translink.ca/v2/gtfsalerts?apikey=[APIKey] 
(No URL, it seems you guys are not providing the alerts feed)

**Comment by mldickens** [comment]
Updated these.
