### ISSUE TITLE
Trip Updates Down Again

### ISSUE THREAD

**Issue by jmiller513** [OpenMobilityData/OpenMobilityData-Public#454]
Trip Updates have been down for over a week for the transit authorities that provide this information. The last update was shown on August 26th.

**Comment by caywood** [comment]
We have confirmed this and are investigating the problem. 

http://transitfeeds.com/p/bart/287

**Comment by jmiller513** [comment]
Any updates on when Trip Updates will be back up and running?

**Comment by ethanpooley** [comment]
This has been fixed, and trip updates should be updated for all agencies within the next 24 hours.

![Screenshot from 2019-10-17 03-42-03](https://user-images.githubusercontent.com/856884/67002471-d6ba4800-f090-11e9-9cc3-27b247bfecb6.png)
