### ISSUE TITLE
Poland > Kraków: Rename GTFS feeds for visibility

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#455]
There are 2 GTFS feeds in Cracow, one for tram schedules and one for bus schedules.

However, [on the website](http://transitfeeds.com/p/mpk-sa-w-krakowie) there is no difference in names between them:
![image](https://user-images.githubusercontent.com/16469272/65813916-9414f680-e1db-11e9-9e22-15669e11e08e.png)

The solution would be to rename:
- [Feed 1104](http://transitfeeds.com/p/mpk-sa-w-krakowie/1104) to "MPK SA w Krakowie Bus GTFS",
- [Feed 1105](http://transitfeeds.com/p/mpk-sa-w-krakowie/1105/latest/routes) to "MPK SA w Krakowie Tram GTFS"

**Comment by fabrice-v** [comment]
Thks for letting us know.
The change was implemented 
See 
https://openmobilitydata.org/p/mpk-sa-w-krakowie/1104
https://openmobilitydata.org/p/mpk-sa-w-krakowie/1105
