### ISSUE TITLE
Refreshed data

### ISSUE THREAD

**Issue by sclmarijt** [OpenMobilityData/OpenMobilityData-Public#458]
Dear,

When i open the feed OVapi Vehicle Positions, there is no refreshed data anymore  for 5 weeks now, when I choose Feed source - save to disk (to get it in readable format). In case I choose for the download option "official download URL" the data is still refreshing.

This is the same issue as earlier this year, bu is this again a temperory thing or are there problems with the MapBox maps?

**Comment by caywood** [comment]
We believe this is now fixed by https://github.com/OpenMobilityData/OpenMobilityData-Public/issues/454#event-2720801906 - please wait 24 hours and everything should be updating again.
