### ISSUE TITLE
GTFS official feed for Navarra, Spain

### ISSUE THREAD

**Issue by MikelArdanaz** [OpenMobilityData/OpenMobilityData-Public#461]
Please complete the following checklist when submitting a new data feed. 
 If you have multiple feeds to submit, please create a separate issue for each of them.
 
 * [ ]  COUNTRY: Spain
 * [ ]  REGION: Navarra
 * [ ]  CITY: Pamplona, Estella, Tudela, Logroño, Soria, ...
 * [ ]  DIRECT DOWNLOAD URL: http://www.navarra.es/appsext/DescargarFichero/default.aspx?codigoAcceso=OpenData&fichero=TransporteInterurbano/gtfs.zip
   This is the URL of the GTFS zip
 * [ ]  FEED ACCESS INFO: https://gobiernoabierto.navarra.es/es/open-data/datos/transporte-publico-interurbano-regular-viajeros-autobus
   This is a web page with more information about the feed (such as licensing or access instructions)
 * [ ]  This feed is reliably updated: YES
 * [ ]  This is an official feed (we try not to include unofficial feeds, but may make exceptions): YES

**Comment by tylerdillard** [comment]
Thank you Mikel, in the future please submit new feeds to http://transitfeeds.com/submit
