### ISSUE TITLE
VTA GTFS Update

### ISSUE THREAD

**Issue by bijanmmarkes** [OpenMobilityData/OpenMobilityData-Public#464]
Please fill out the following if an existing feed has a new download URL:

URL on OpenMobilityData: http://transitfeeds.com/p/vta/45 which is currently pulling from http://www.vta.org/sfc/servlet.shepherd/document/download/069A0000001NUea, this location is no longer being updated since we have completely redesigned our website. Our new permanent link is below:

## New download URL (permanent direct link): 

GTFS: https://gtfs.vta.org/gtfs_vta.zip
Policy/Information: https://gtfs.vta.org

Thank you.

**Comment by bijanmmarkes** [comment]
Any update on this?

**Comment by tylerdillard** [comment]
Thanks @bijanmmarkes . Was OOO for the holiday, but have updated now.
