### ISSUE TITLE
invalid feed shows no errors on transitfeeds

### ISSUE THREAD

**Issue by blackmad** [OpenMobilityData/OpenMobilityData-Public#467]
https://transitfeeds.com/p/trimet/43/20200108

This feed was invalid, "[it] was published with a route naming issue (it was missing both the short and long names for line 20, starting March 1st)" but transitfeeds showed no errors for it. Is that something the validation should have caught?

**Comment by Cristhian-HA** [comment]
Hello @blackmad,

Thank you for contacting us, the present validation of the site is incomplete. We will improve it with the next version of the site with the work we are currently doing [there](https://github.com/MobilityData/gtfs-validator)

Have a great day!
