### ISSUE TITLE
Denmark GTFS new URL

### ISSUE THREAD

**Issue by gtfs0** [OpenMobilityData/OpenMobilityData-Public#468]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/rejseplanen/705
- [ ] New download URL (direct link): http://www.rejseplanen.info/labs/GTFS.zip

**Comment by Cristhian-HA** [comment]
Hello @gtfs0,

Thank you for sending the new updates. We have made the updates on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
