### ISSUE TITLE
Add a warning detector for stop coordinates

### ISSUE THREAD

**Issue by HendX** [OpenMobilityData/OpenMobilityData-Public#47]
It is fairly trivial to detect when a coordinate is massively different to other coordinates.

This should allow for a fairly spread system (e.g. something like Amtrak) where there may be large differences.

For example, this extract from Riverside Transit Agency indicates a stop that has an invalid coordinate:

```
33.6239153,,-117.3204373,00810130,,Grand FS Stoneman,0
33.9534595,,-117.3931135,01009315,,Central FS De Anza,0
33.7797106,,-116.9511796,03210075,,Hewitt FS Seventh,0
33.6067,,-177.29245,00800182,,Grand Opp. Hixon,0
```

The final record should be -117, not -177.

**Comment by HendX** [comment]
Perhaps this could be grouped by agency within a feed, or create general groups of locations automatically, and a flag a coordinate that sits by itself.

**Comment by caywood** [comment]
GTFS validators catch these kinds of errors. https://github.com/CUTR-at-USF/awesome-transit#gtfs-validators

Would accept a patch to integrate one into OMD (TransitLand did that on their site).
