### ISSUE TITLE
Update Brazil, BHTRANS data

### ISSUE THREAD

**Issue by RockyTV** [OpenMobilityData/OpenMobilityData-Public#470]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

They have two different GTFS feeds, one of the main bus lines and other one for supplementary bus lines, both under BHTRANS, the same company.

- [ ] URL on OpenMobilityData: http://transitfeeds.com/p/bhtrans
- [ ] New download URL (direct link):
  - [ ] Main: https://ckan.pbh.gov.br/dataset/77764a7e-63fc-4111-ace3-fb7d3037953a/resource/f0fa78dc-74c3-49fa-8971-c310a76a07fa/download/gtfsfiles.zip
  - [ ] supplementary: https://ckan.pbh.gov.br/dataset/af0c47bb-5a82-4ae1-874f-e45dea1397ff/resource/b2a9341e-4471-45cc-a8c0-11be805590bc/download/gtfsfiles.zip
- [ ] New feed information URL: 
  - [ ] Main: https://dados.pbh.gov.br/dataset/gtfs-estatico-do-sistema-convencional
  - [ ] Supplementary: https://dados.pbh.gov.br/dataset/feed-gtfs-estatico-do-sistema-suplementar

I've tried submitting it via the website a few times, both more than a month ago but nothing changed.

**Comment by gabrielvazdemelo** [comment]
Great. I was just doing that. Did you have any news? I just submitted also the realtime.

**Comment by Cristhian-HA** [comment]
Hello @RockyTV 

Thank you for sending the new updates. We have made the changes on our side for the Main feeds. However, supplementary is a new feed and we will add it to the next version of the site as we currently do not support adding new feed to the current version.

Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
