### ISSUE TITLE
UK GTFS stop_times.txt

### ISSUE THREAD

**Issue by PieroMatassoni** [OpenMobilityData/OpenMobilityData-Public#471]
the GB Bus Services GTFS stop_time.txt can not be downloaded.
When I try to view the file got error
https://openmobilitydata-data.s3-us-west-1.amazonaws.com/public/feeds/traveline/1033/20190619/original/stop_times.txt

![Stop_Times](https://user-images.githubusercontent.com/60262771/73075590-3015ec80-3eb4-11ea-8d3b-e24292aad0f7.JPG)

Could you please suggest another way to get it?

Thanks,

Piero

**Comment by Cristhian-HA** [comment]
Hello @PieroMatassoni,
Thank you for contacting us, unfortunately, there is no fix nor alternate way to download that information from the current version of the site.
Have a great day!
