### ISSUE TITLE
Poland: SKM Warszawa and PKP SKM Trójmiasto confusion.

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#472]
See #380.

[Feed 1160, PKP SKM w Trójmieście](http://transitfeeds.com/p/pkp-szybka-kolej-miejska-w-trojmie-cie/1116), <https://przyjazdy.pl/latest/skmt.zip>, is marked as deprecated, even tough the feed is alive and well.

[Feed 790, SKM Warszawa](http://transitfeeds.com/p/szybka-kolej-miejska-w-warszawie/790) is deprecated, as data was merged into [Feed 720, ZTM Warszawa](http://transitfeeds.com/p/ztm-warszawa/720). However the website incorrectly shows data from PKP SKM w Trójmieście.

**Comment by fabrice-v** [comment]
Hi, thks for letting us know.
We removed the deprecation flag from 1160.
We deprecated 790.
As for 720, we understand there is an issue with the data source being wrong but we couldn't figure out the correct URL. Would you happen to be able to provide it to us so we can fix the issue?

**Comment by MKuranowski** [comment]
There's nothing wrong with 720. I only mentioned it, because the deprecation message for 790 says "No alternative feed has been identified."  
720 is the alternative feed; data from 790 was put into feed 720.

**Comment by fabrice-v** [comment]
Alright, 790 deprecation message was updated to reflect the situation.
Thks for letting us know.
