### ISSUE TITLE
Template pages for cities/agencies without data

### ISSUE THREAD

**Issue by caywood** [OpenMobilityData/OpenMobilityData-Public#476]
It's funny that you still see City Go Round sometimes when you google search "CityName GTFS" or "TransitAgencyName GTFS", even though it's defunct for several years now.

Once we have [imported the hierarchy](https://github.com/OpenMobilityData/OpenMobilityData-Public/issues/474), it should be possible to create placeholder pages for cities and agencies.

TransitLand created placeholders here: https://transit.land/news/2017/10/12/placeholder-operators.html

**Comment by Cristhian-HA** [comment]
Hello,

We were unable to reproduce the issue about doing a google search and seeing City Go Round , however we will take a look at your second issue and study the use case.

Have a great day!
