### ISSUE TITLE
Unsupported attributions.txt

### ISSUE THREAD

**Issue by MKuranowski** [OpenMobilityData/OpenMobilityData-Public#478]
The website shows `attributions.txt` files as unrecognized, even tough it is a part of the GTFS spec.

![image](https://user-images.githubusercontent.com/16469272/73590823-4f7dcc80-44e7-11ea-9ea9-2e4c3ad95560.png)

The GTFS spec: <https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#attributionstxt>  
Example feeds: [Denmark: Rejseplanen](http://transitfeeds.com/p/rejseplanen/705/latest/file/attributions.txt) or [Poland: ZTM Warszawa](http://transitfeeds.com/p/ztm-warszawa/720/latest/file/attributions.txt)

**Comment by Cristhian-HA** [comment]
Hello @MKuranowski,

Thank you for contacting us. Unfortunately, this is not currently supported but we will take in consideration for the future versions on the site.

Have a great day!
