### ISSUE TITLE
Fix feed url: MPK Kraków feed not updating

### ISSUE THREAD

**Issue by filipwodnicki** [OpenMobilityData/OpenMobilityData-Public#479]
## UPDATE EXISTING FEED:

Kraków has a new download link.

URL on OpenMobilityData:
http://transitfeeds.com/p/mpk-sa-w-krakowie/1105

New download URL (direct link):
Buses: [ftp://ztp.krakow.pl/pliki-gtfs/GTFS_KRK_A.zip](ftp://ztp.krakow.pl/pliki-gtfs/GTFS_KRK_A.zip)
Trams: [ftp://ztp.krakow.pl/pliki-gtfs/GTFS_KRK_T.zip](ftp://ztp.krakow.pl/pliki-gtfs/GTFS_KRK_T.zip)

Please label schedule links accordingly for Buses and Trams (referencing issue #455). Thanks

**Comment by fabrice-v** [comment]
Hi,
Thks for letting us know.
URLs were updated and the new data should be on the site in the next 24 hours. Please reopen this issue if that is not the case.
Changes in #455 have also been implemented.
