### ISSUE TITLE
Germany, NRW, Verkehrsverbund-Rhein-Sieg (VRS) changed Download URLs

### ISSUE THREAD

**Issue by mastacheata** [OpenMobilityData/OpenMobilityData-Public#480]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL on OpenMobilityData: https://openmobilitydata.org/p/verkehrsverbund-rhein-sieg/835
- [x] New download URL (direct link): http://download.vrsinfo.de/gtfs/Google_Transit_mit_GlobalIDs.zip

There's no information about what Global-IDs means with respect to their feed, but I think it's safe to assume they use UUIDs instead of increasing numbers for IDs in that dataset.

Alternatively there's a version without this global ID thing at this URL: http://download.vrsinfo.de/gtfs/google_transit.zip

**Comment by fabrice-v** [comment]
Hi,
Thks for letting us know. We used the second URL you provided and the new data shall be on the site in the next 24h. Please reopen this issue if that is not the case.
