### ISSUE TITLE
SBB CFF FFS new link

### ISSUE THREAD

**Issue by stebazzi** [OpenMobilityData/OpenMobilityData-Public#481]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [X] URL on OpenMobilityData: http://transitfeeds.com/p/sbb-cff-ffs/793
- [X] New download URL (direct link): https://opentransportdata.swiss/dataset/timetable-2020-gtfs/permalink

**Comment by fabrice-v** [comment]
Hi, thks for letting us know. The URL was updated and the new data shall appear on the site in the next 24h. Please reopen this issue if that is not the case.
