### ISSUE TITLE
Sweden (Trafiklab) Regional GTFS URL change

### ISSUE THREAD

**Issue by Bertware** [OpenMobilityData/OpenMobilityData-Public#482]
Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/trafiklab/1183 (also affects https://transitfeeds.com/p/trafiklab/1245)
- [ ] New download URL (direct link): https://opendata.samtrafiken.se/gtfs/vt/vt.zip

A key, passed in a ?key=... query parameter, must be obtained by registering at trafiklab.se, creating a project and adding a key. The key is unique for static and realtime data. The key can be upgraded to the gold level, just mention it's for transitfeeds. This has been done before, but now both keys and URLs change in order to prepare moving from beta to stable. 

See also #401 

Note:
The same key can also be used to obtain data from other regions. The links for static data can be found at https://www.trafiklab.se/node/26738/documentation , while the links for realtime data can be found at https://www.trafiklab.se/node/26806/documentation .

**Comment by fabrice-v** [comment]
Hi, thks for letting us now. We could update https://transitfeeds.com/p/trafiklab/1183 with success and the new data should be available on there in the next 24 hours. We could not understand how to update https://transitfeeds.com/p/trafiklab/1245, should it be the same URL and the same data?

**Comment by Bertware** [comment]
Hi Fabrice,

All "GTFS Regional" static files are available through `https://opendata.samtrafiken.se/gtfs/<operator>/<operator>.zip` . An API key is required, I saw your request and raised the key to the gold level.


All "GTFS Regional" realtime files are available through `https://opendata.samtrafiken.se/gtfs-rt/<operator>/ServiceAlerts.pb` , `https://opendata.samtrafiken.se/gtfs-rt/<operator>/TipUpdates.pb` and `https://opendata.samtrafiken.se/gtfs-rt/<operator>/VehiclePositions.pb`  . A **different** API key is required, but I went ahead and added a gold level API key to your project, so if you go to your project you should see the new API key there.

Operators which have static files (abbreviation for urls, i put the human readable name in brackets):
 - sl (SL)
 - ul (UL)
- sormland (Sörmlandstrafiken)
- otraf (Östgötatrafiken)
- krono (Länstrafik Kronoberg)
- klt (Kalmar Länstrafik)
- gotland (Gotland)
- blekinge (Blekingetrafiken)
- skane (Skånetrafiken)
- halland (Hallandstrafiken)
- vt (Västtrafik)
- varm (Värmlandstrafiken and Karlstadsbuss)
- orebro (Örebro)
- vl (Västmanland)
- dt (Dalatrafiken)
- xt (X-trafik)
- dintur (DinTur (Västernorrland))
- sj (SJ, Snälltåget and Tågab)

Operators which have realtime ServiceAlerts and TripUpdates:
- sl
- ul
- otraf
- klt
- skane
- varm
- dt
- xt

Operators which have realtime VehiclePositions:
- ul
- otraf
- klt
- skane
- varm
- dt
- xt

**Comment by fabrice-v** [comment]
Hi,
Thks for the details. 
As to minimize the risk of error, could you please provide as a reply to this issue, for each feed

- the openmobilitydata.org feed url (for example https://openmobilitydata.org/p/societe-de-transport-de-montreal/39)
- the associated data url in its complete form except for the key (for example: http://www.stm.info/sites/default/files/gtfs/gtfs_stm.zip?key=[YOUR_KEY_HERE]), with some details on where to find the correct key on the partially translated key registration website.

Then we'll be able to proceed.

As for feeds that aren't registered yet, please go through the form available on the website.

**Comment by Bertware** [comment]
https://transitfeeds.com/p/trafiklab/1183 -> https://opendata.samtrafiken.se/gtfs/vt/vt.zip?key=... , the name should be "GTFS Regional (beta) - Västtrafik"  instead of "GTFS Regional (beta) - VT".

https://transitfeeds.com/p/trafiklab/1245 -> 
- https://opendata.samtrafiken.se/gtfs-rt/otraf/ServiceAlerts.pb?key=... 
- https://opendata.samtrafiken.se/gtfs-rt/otraf/TipUpdates.pb?key=... 
- https://opendata.samtrafiken.se/gtfs-rt/otraf/VehiclePositions.pb?key=...

I'll submit the other ones through the form.

**Comment by Cristhian-HA** [comment]
Hello @Bertware,
Unfortunately at this moment we do not have the resources to process this request, however we are working on a new version of the site that should allow the addition of the datasets.
Have a great day!
