### ISSUE TITLE
New link of Lignes D'azur

### ISSUE THREAD

**Issue by stebazzi** [OpenMobilityData/OpenMobilityData-Public#484]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x ] URL on OpenMobilityData: https://transitfeeds.com/p/lignes-dazur/738
- [x ] New download URL (direct link): http://opendata.nicecotedazur.org/data/dataset/export-quotidien-au-format-gtfs-du-reseau-de-transport-lignes-d-azur/resource/aacb4eea-d008-4b13-b17a-848b8ced7e03/download

**Comment by fabrice-v** [comment]
L'URL a été mise à jour et les nouvelles données seront sur le site d'ici les prochaines 24h. Merci de rouvrir cette issue si ça n'est pas le cas.
