### ISSUE TITLE
New Caltrain feed

### ISSUE THREAD

**Issue by acnetj** [OpenMobilityData/OpenMobilityData-Public#485]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://transitfeeds.com/p/caltrain/122
- [ ] New download URL (direct link): http://data.trilliumtransit.com/gtfs/caltrain-ca-us/caltrain-ca-us.zip

**Comment by fabrice-v** [comment]
The URL has been updated and the new data should appear on the site in the next 24 hours. Please reopen this issue if that is not the case.
