### ISSUE TITLE
New feed URL: Agenzia Mobilità Ambiente Territorio

### ISSUE THREAD

**Issue by jsteelz** [OpenMobilityData/OpenMobilityData-Public#486]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://amat-mi.it/it/downloads/data/gtfs/current/Export_OpenDataTPL_Current.zip (the page on OpenMobilityData is https://openmobilitydata.org/p/agenzia-mobilita-ambiente-territorio/341 )
- [ ] New download URL (direct link): https://www.amat-mi.it/downloads/gtfs/gtfs.zip

If application:

- [ ] New feed information URL: _________________________

**Comment by fabrice-v** [comment]
Hey,
Thks for letting us now. Could you provide us the URL of the feed on the site (for example https://openmobilitydata.org/p/bay-area-transit-authority/1144) so we can do the update?

**Comment by jsteelz** [comment]
Done 👍

**Comment by fabrice-v** [comment]
Thank you very much. The URL was updated and new data should appear on the site in the next 24 hours. Please reopen this issue if that is not the case.
