### ISSUE TITLE
Caltrain data is wrong

### ISSUE THREAD

**Issue by colinmcglynn** [OpenMobilityData/OpenMobilityData-Public#487]
It looks like somehow Samtrans data got loaded into the caltrain feed

https://transitfeeds.com/p/caltrain/122/latest

**Comment by Cristhian-HA** [comment]
Hello @colinmcglynn,
Thank you for contacting us, would you be able to provide more information on this problem? is the feed URL incorrect?

**Comment by colinmcglynn** [comment]
looks like it's resolved now, thanks!
