### ISSUE TITLE
NEW FEED URL: Bay Area Transportation Authority

### ISSUE THREAD

**Issue by calhouncole** [OpenMobilityData/OpenMobilityData-Public#488]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://transitfeeds.com/p/bay-area-transit-authority/1144
- [ ] New download URL (direct link): http://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/5109/BATA_GTFS.zip

If application:

- [ ] New feed information URL: _________________________

**Comment by fabrice-v** [comment]
The URL was updated and the new data should appear on the site in the next 24h max. Please reopen this issue if that's not the case.
