### ISSUE TITLE
UPDATE FEED URL: Metz GTFS

### ISSUE THREAD

**Issue by mxbssn** [OpenMobilityData/OpenMobilityData-Public#489]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/metz-metropole/850
- [ ] New download URL (direct link): https://si.metzmetropole.fr/fiches/opendata/gtfs_current.zip

If application:

- [ ] New feed information URL: https://www.data.gouv.fr/fr/datasets/r/9bff120f-d1ba-4753-83cb-6d598ebe2e60

**Comment by fabrice-v** [comment]
La nouvelle URL a bien été ajoutée et les données seront sur le site d'ici 24h maximum. Merci de rouvrir cette 'issue' si ça n'est pas le cas.
