### ISSUE TITLE
Update feed: RTC Quebec CIty

### ISSUE THREAD

**Issue by transitquebec** [OpenMobilityData/OpenMobilityData-Public#490]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://www.rtcquebec.ca/Portals/0/Admin/DonneesOuvertes/googletransit.zip
- [ ] New download URL (direct link):https://cdn.rtcquebec.ca/Site_Internet/DonneesOuvertes/googletransit.zip

If application:

- [ ] New feed information URL: _________________________

**Comment by fabrice-v** [comment]
The `URL on OpenMobilityData:` is invalid (it should point to an existing feed on the site). Please provide a valid feed URL for us to do the update.
Thks
