### ISSUE TITLE
API Returns 404 When Requesting Multiple GTFS Files 

### ISSUE THREAD

**Issue by rickl4** [OpenMobilityData/OpenMobilityData-Public#491]
When using the `getFeedVersions` call for the API, I'm able to successfully get results for the first transit agency, but for any subsequent transit agency, I get a 404 error. This happens when I loop through a list of agency_ids that I get from the `getFeeds` call.

I've managed to replicate this for different regions, and for different sets of agencies. If its an issue on my end, I'm wondering how I can mitigate this issue.

Below is a snipped I used to ping the api

```python
for row in id_lst:
    for attempt in range(2):

        try:
            response = s.get(
                url+'/v1/getFeedVersions',
                params = {'key': key, 'feed' : row, 'limit' : 10

                }
            )
            sleep(1)
            feed_info = response.json()['results']['versions']


```
where id_lst is a python list of all the agency_ids I want to use.

**Comment by Cristhian-HA** [comment]
Hello @rickl4,
Thank you for sending us the details. We are currently working on a new version of the site and API's.
Have a great day!
