### ISSUE TITLE
Unitrans (Davis, CA) updated URL

### ISSUE THREAD

**Issue by collinkemp** [OpenMobilityData/OpenMobilityData-Public#493]
The current GTFS link for Unitrans has not been updated for two years.  See below for a link to more recent static data.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://iportal.sacrt.com/GTFS/Unitrans/google_transit.zip
- [ ] New download URL (direct link): https://unitrans.ucdavis.edu/media/gtfs/Unitrans_GTFS.zip

**Comment by fabrice-v** [comment]
`URL on OpenMobilityData` is invalid. Please provide a valid URL for us to do the update.
Thks,
