### ISSUE TITLE
RTA Maryland GTFS static URL update

### ISSUE THREAD

**Issue by colemccarren** [OpenMobilityData/OpenMobilityData-Public#494]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/regional-transportation-agency-of-central-maryland/574
- [ ] New download URL (direct link): data.trilliumtransit.com/gtfs/centralmarylandrta-md-us/centralmarylandrta-md-us.zip

**Comment by fabrice-v** [comment]
`New download URL (direct link)` was assumed to be served over https : data.trilliumtransit.com/gtfs/centralmarylandrta-md-us/centralmarylandrta-md-us.zip
The URL was updated and the new feed should appear on the site in the next 24 hours max. Please reopen this issue if that's not the case.
