### ISSUE TITLE
UPDATE EXISTING FEED: MASSPORT

### ISSUE THREAD

**Issue by MPA-RPENA** [OpenMobilityData/OpenMobilityData-Public#495]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://data.trilliumtransit.com/gtfs/loganexpress-ma-us/loganexpress-ma-us.zip
- [ ] New download URL (direct link):http://www.massport.com/media/4109/massport_gtfs.zip

This is for https://transitfeeds.com/p/massport/1137

**Comment by fabrice-v** [comment]
`URL on OpenMobilityData` is invalid (it should point to the feed URL on the site). Please provide a valid URL for us to do the update.
Thks,
