### ISSUE TITLE
Update DAKK GTFS feed

### ISSUE THREAD

**Issue by csehpacilla** [OpenMobilityData/OpenMobilityData-Public#496]
New information about the following feed: https://transitfeeds.com/p/dakk/625

- [ ] URL on OpenMobilityData: http://members.upc.hu/cseh.attila/google_transit.zip
- [ ] New download URL (direct link): http://szegedimenetrend.hu/google_transit.zip

- [ ] New feed information URL: http://szegedimenetrend.hu

**Comment by fabrice-v** [comment]
The `URL on OpenMobilityData` is invalid. Please provide a valid URL for us to be able to make the update.
Thks

**Comment by csehpacilla** [comment]
The new download URL is valid:
http://szegedimenetrend.hu/google_transit.zip

**Comment by fabrice-v** [comment]
Yes, wht we'd need is the URL of the feed to which it applies. As an example https://openmobilitydata.org/p/societe-de-transport-de-montreal/39

**Comment by csehpacilla** [comment]
Sorry, the OpenMobilityData URL is:
https://openmobilitydata.org/p/dakk/625

**Comment by fabrice-v** [comment]
No problem, I can see how the wording can be confusing :)
The URL has been updated and new data should dhow up in the next 24h, please reopen this issue if that is not the case.
