### ISSUE TITLE
St Albert, AB New URL

### ISSUE THREAD

**Issue by useless2764** [OpenMobilityData/OpenMobilityData-Public#497]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL on OpenMobilityData: https://openmobilitydata.org/p/st-albert-transit/498
- [x] New download URL (direct link): https://stalbert.ca/site/assets/files/3840/google_transit.zip
Info/Rules: https://stalbert.ca/city/transit/tools/open-data-gtfs/

**Comment by fabrice-v** [comment]
The feed URL has been updated and the new version shall appear in the next 24 hours. Please reopen this issue if that's not the case.
