### ISSUE TITLE
Update existing feed

### ISSUE THREAD

**Issue by steveplesha** [OpenMobilityData/OpenMobilityData-Public#498]
Please fill out the following if an existing feed has a new download URL:

 URL on OpenMobilityData: https://transitfeeds.com/p/south-shore-line/863
 New download URL (direct link): http://www.mysouthshoreline.com/google/google_transit.zip

**Comment by fabrice-v** [comment]
The URL was updated and new versions of the feed should appear in the coming hours (max 24). Please reopen this issue if that's not the case.
