### ISSUE TITLE
UPDATE FEED URL

### ISSUE THREAD

**Issue by miguelf88** [OpenMobilityData/OpenMobilityData-Public#500]
Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://openmobilitydata.org/p/piedmont-authority-for-regional-transportation/538/latest
- [ ] New download URL (direct link): http://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/5137/gtfs.zip

**Comment by fabrice-v** [comment]
The URL was updated. If available, the new GTFS.zip file shall appear in the coming hours (24 hours max)
