### ISSUE TITLE
Metro Transit (Minneapolis MN) Feed not updating

### ISSUE THREAD

**Issue by botanize** [OpenMobilityData/OpenMobilityData-Public#501]
- [ ] URL on OpenMobilityData: https://transitfeeds.com/p/metro-transit/179
- [ ] New download URL (direct link): https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_state_metc/trans_transit_schedule_google_fd/csv_trans_transit_schedule_google_fd.zip

The "Official Download URL" has the latest information (2020-07-18), but the "latest" feed is dated 2020-07-02

**Comment by fabrice-v** [comment]
The situation should now be resolved with latest feed dated 2020-07-28
