### ISSUE TITLE
Brampton Transit GTFS update not being processed

### ISSUE THREAD

**Issue by ethanpooley** [OpenMobilityData/OpenMobilityData-Public#503]
@fabrice-v Just wanted to enter a real-world example of something not being processed and that leading to problems. We are using some Brampton Transit data (https://openmobilitydata.org/p/brampton-transit/35), and in calls with them this week they noted that the OMD website hadn't recognized/processed their most recent update scheduled to go live this morning.

We were able to fix that for them (in our application, anyway) by going straight to their GTFS source file for the time being. Just noting it here.

**Comment by fabrice-v** [comment]
We are investigating the issue, thks.
@maximearmstrong

**Comment by fabrice-v** [comment]
The issue has been fixed and the latest feed is now available:
https://openmobilitydata.org/p/brampton-transit/35/latest

Some feeds are still backlogged and should be updated in the coming hours.

**Comment by ethanpooley** [comment]
Nice! Thank you both.
