### ISSUE TITLE
CMRT feed deprecated (MD, USA)

### ISSUE THREAD

**Issue by colemccarren** [OpenMobilityData/OpenMobilityData-Public#507]
I noticed that deprecated flags are available to assign to feeds.

In the state of Maryland, USA, the [CMRT](https://openmobilitydata.org/p/central-maryland-regional-transit/297) feed was imperfectly superseded by the [RTA](https://openmobilitydata.org/p/regional-transportation-agency-of-central-maryland/574) feed, a couple years back.

Can a deprecated flag be assigned to the [CMRT](https://openmobilitydata.org/p/central-maryland-regional-transit/297) feed?

**Comment by fabrice-v** [comment]
Hi, thks for reporting. Yes, such changes can be made, the result is as follow:
![image](https://user-images.githubusercontent.com/55884852/90149349-63d23a00-dd52-11ea-9fcb-48353a405ea7.png)
