### ISSUE TITLE
UPDATE EXISTING FEED — RIPTA

### ISSUE THREAD

**Issue by chris-sarli** [OpenMobilityData/OpenMobilityData-Public#508]
## UPDATE EXISTING FEED:

- [ ] URL on OpenMobilityData: [https://openmobilitydata.org/p/rhode-island-public-transit-authority/363](https://openmobilitydata.org/p/rhode-island-public-transit-authority/363)
- [x] New download URL (direct link): [https://www.ripta.com/wp-content/uploads/2020/08/google_transit.zip](https://www.ripta.com/wp-content/uploads/2020/08/google_transit.zip)

**Comment by Cristhian-HA** [comment]
Hello @chris-sarli,

Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
