### ISSUE TITLE
Typo for "Weiner Linien" feed in Vienna, Austria

### ISSUE THREAD

**Issue by ServusWorld** [OpenMobilityData/OpenMobilityData-Public#510]
The feed https://openmobilitydata.org/p/weiner-lienen is wrong-written, it should be called "Wiener Linien" (i and e are interchanged).
("Weiner Linien" actually means "wine's routes" :D)

**Comment by Cristhian-HA** [comment]
Hello,
Thanks for letting us know, however your link has been deprecated. We can change the name but I am not sure it will be helpful since it is deprecated.
Regards,
