### ISSUE TITLE
Update LADOT feed location

### ISSUE THREAD

**Issue by stevenmwhite** [OpenMobilityData/OpenMobilityData-Public#511]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL on OpenMobilityData: https://openmobilitydata.org/p/ladot-transit-services/303

- [ ] New download URL (direct link): https://ladotbus.com/gtfs
- [ ] RT Vehicle Positions URL: https://ladotbus.com/gtfs-rt/vehiclepositions
- [ ] RT Trip Updates URL: https://ladotbus.com/gtfs-rt/tripupdates
- [ ] RT Alerts URL: https://ladotbus.com/gtfs-rt/alerts

**Comment by fabrice-v** [comment]
Hi,

thks for reporting. We could update the feed URL and the result should be visible on the site in the next few hours.

We are having trouble locating existing feeds for the RT URLs you provided. Are they on the site?

**Comment by stevenmwhite** [comment]
@fabrice-v no, the openmobilitydata does not currently list the RT feeds.

**Comment by fabrice-v** [comment]
Ok. In that case they have to be submitted through that interface for potential addition to the site
https://openmobilitydata.org/submit

Be aware that it might take a while before we'll be able to proceed with the addition. I'll keep this issue open.

Thks again

**Comment by stevenmwhite** [comment]
Ok will do. As far as the static goes, that url can be updated first right? (The existing listed location is very out of date.)

**Comment by fabrice-v** [comment]
Yes, it has been updated and the new data should be on the site in the next 24 hours. Please report here if that is not the case then
