### ISSUE TITLE
MTA Maryland - new feed structure/location

### ISSUE THREAD

**Issue by torgren-fitp** [OpenMobilityData/OpenMobilityData-Public#514]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

MTA Maryland has split one comprehensive GTFS feed into 5 smaller feeds. More info here: https://www.mta.maryland.gov/developer-resources

- [x] URL on OpenMobilityData: https://transitfeeds.com/p/mta-maryland/247
- [x] New download URL (direct link): 
Local bus: https://mdotmta-gtfs.s3.amazonaws.com/mdotmta_gtfs_localbus.zip
Light RailLink: https://mdotmta-gtfs.s3.amazonaws.com/mdotmta_gtfs_lightrail.zip
Metro SubwayLink: https://mdotmta-gtfs.s3.amazonaws.com/mdotmta_gtfs_metro.zip
MARC Train: https://mdotmta-gtfs.s3.amazonaws.com/mdotmta_gtfs_marc.zip
Commuter Bus: https://mdotmta-gtfs.s3.amazonaws.com/mdotmta_gtfs_commuterbus.zip

**Comment by Cristhian-HA** [comment]
Hello @torgren-fitp,

Thank you for contacting us. Unfortunately our site can only support one link per URL on OpenMobilityData, can you please let me know which one should I use?

Thank you!
