### ISSUE TITLE
United Kingdom Bus, Subway, Light Rail GTFS feed

### ISSUE THREAD

**Issue by markerpen** [OpenMobilityData/OpenMobilityData-Public#515]
The UK's Department of Transport has created a new online service for open bus data, and have released a UK-wide GTFS feed.

The UK-wide GTFS feed can be downloaded here: https://data.bus-data.dft.gov.uk/timetable/download/gtfs-file/all/
More information and smaller area-specific feeds here: https://data.bus-data.dft.gov.uk/timetable/download/

The feed includes all bus routes, as well as all London Underground, tram and light rail services. 

The feed does not include:
- National Rail train services
- Isle of Man bus services
- Jersey & Guernsey bus services
- Northern Ireland bus and train services

**Comment by Cristhian-HA** [comment]
Hello @markerpen ,

Thank you for contacting us. Would you be able to provide a valid `URL on OpenMobilityData` for us to do the update? (it should point to the feed URL on the site).

Thank you!
