### ISSUE TITLE
Metro Transit (Minneapolis, MN) Feed not Updating

### ISSUE THREAD

**Issue by botanize** [OpenMobilityData/OpenMobilityData-Public#516]
## UPDATE EXISTING FEED:

- [x] URL on OpenMobilityData: <https://transitfeeds.com/p/metro-transit/179>
- [x] New download URL (direct link): <https://svc.metrotransit.org/mtgtfs/gtfs.zip>

The old URL now links to the new hosting location instead of the direct download link.

**Comment by Cristhian-HA** [comment]
Hello @botanize 
Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
