### ISSUE TITLE
New URL for Oakville Transit

### ISSUE THREAD

**Issue by useless2764** [OpenMobilityData/OpenMobilityData-Public#518]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL on OpenMobilityData: https://transitfeeds.com/p/oakville-transit/615
- [x] New download URL (direct link): https://www.arcgis.com/sharing/rest/content/items/d78a1c1ad6a940009de8b68839a8f606/data

**Comment by Cristhian-HA** [comment]
Hello @useless2764 
Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.
Have a great day!
