### ISSUE TITLE
New sbb-cff-ffs link

### ISSUE THREAD

**Issue by stebazzi** [OpenMobilityData/OpenMobilityData-Public#519]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL on OpenMobilityData: https://transitfeeds.com/p/sbb-cff-ffs/793
- [x] New download URL (direct link): https://opentransportdata.swiss/de/dataset/timetable-2021-gtfs2020/permalink

If application:

- [ ] New feed information URL: _________________________

**Comment by Cristhian-HA** [comment]
Hello @stebazzi 

Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
