### ISSUE TITLE
Update Modesto Area Express (MAX) feed locations

### ISSUE THREAD

**Issue by mcplanner** [OpenMobilityData/OpenMobilityData-Public#520]
## NEW FEEDS:

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).
**This link is broken.**

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: http://transitfeeds.com/p/modesto-area-express
- [ ] New download URL (direct link):

Static: https://www.modestoareaexpress.com/preview-gtfs.zip
Vehicle Position: http://max.availtec.com/InfoPoint/GTFS-Realtime.ashx?Type=VehiclePosition
Rider Alerts: http://max.availtec.com/InfoPoint/GTFS-Realtime.ashx?Type=Alert
Trip Updates: http://max.availtec.com/InfoPoint/GTFS-Realtime.ashx?Type=Tripupdate

**Comment by Cristhian-HA** [comment]
Hello Ruth,
Thank you for contacting us. Unfortunately our site can only support one link per URL on OpenMobilityData, can you please let me know which one should I use? Also is this change for the [MAX GTFS](https://openmobilitydata.org/p/modesto-area-express/1280) or for the [MAX Trip Updates](https://openmobilitydata.org/p/modesto-area-express/928)?
Regards,

**Comment by mcplanner** [comment]
Hi Cristhian,
These are the links the agency provided me for their static and real time
feeds.
Are you saying that OMD can only host Trip Updates, Vehicle Positions, or
Alerts, but not all three?
Thank you,

**Comment by fabrice-v** [comment]
> ## NEW FEEDS:
> To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).
> **This link is broken.**
It is not. You do need to login with GitHub to see the interface, as stated in the `401 - Unauthorized` message
![image](https://user-images.githubusercontent.com/55884852/99140042-1775ef00-260c-11eb-84ba-30d3fd2c6d2a.png)

**Comment by f8full** [comment]
> ## NEW FEEDS:
> To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).
> **This link is broken.**

It is not. You do need to login with GitHub to see the interface, as stated in the `401: Unauthorized` message
![image](https://user-images.githubusercontent.com/55884852/99140042-1775ef00-260c-11eb-84ba-30d3fd2c6d2a.png)

**Comment by Cristhian-HA** [comment]
Hello Ruth,

Sorry for my late response. What I am trying to say is that on OpenMobilityData we can only support updating one link that contains all the necessary information for each feed. please see below screen shot. So in your original message you gave me 4 different links which unfortunately I cannot process. Also you can submit new feed requests here [Submit a Feed](https://transitfeeds.com/submit). I hope this helps!
![Screen Shot 2020-11-20 at 11 25 09 AM](https://user-images.githubusercontent.com/71390545/99824171-57b10200-2b23-11eb-9740-78d23f9bbe63.png)
