### ISSUE TITLE
NJ Transit rail and bus data not reflecting the latest published data

### ISSUE THREAD

**Issue by kohzyixn** [OpenMobilityData/OpenMobilityData-Public#521]
Hi!

The NJ Transit rail and bus data on transitfeeds below seem to reflect older sets of NJT published GTFS data.

NJT Rail on Transitfeeds: http://transitfeeds.com/p/nj-transit/408/latest (expired Oct 17)
NJT Bus on Transitfeeds: http://transitfeeds.com/p/nj-transit/409/latest (expired Oct 26)

It looks like NJT has since published newer versions of both sets of GTFS data
https://www.njtransit.com/bus_data.zip
https://www.njtransit.com/rail_data.zip

**Comment by Cristhian-HA** [comment]
Hello @kohzyixn 

Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
