### ISSUE TITLE
Update RTD Denver GTFS & GTFS-RT Feed Locations

### ISSUE THREAD

**Issue by wmcb91** [OpenMobilityData/OpenMobilityData-Public#525]
## UPDATE EXISTING FEED:
On Tuesday, December 1, RTD updated the locations of its GTFS and GTFS-RT files. It also removed the Basic Auth requirement for its GTFS-RT feeds. This issue reflects those changes.

### GTFS Static Feed
- [ ] URL on OpenMobilityData: https://openmobilitydata.org/p/rtd-denver/188
- [x] New download URL (direct link): https://rtd-denver.com/files/gtfs/google_transit.zip
- [x] New feed information URL: https://www.rtd-denver.com/business-center/open-data/gtfs-developer-guide

### Trip Updates
- [ ] URL on OpenMobilityData: https://openmobilitydata.org/p/rtd-denver/610
- [x] New download URL (direct link): https://www.rtd-denver.com/files/gtfs-rt/TripUpdate.pb
- [x] New feed information URL: https://www.rtd-denver.com/business-center/open-data/gtfs-developer-guide#gtfs-realtime-feeds

### Vehicle Positions
- [ ] URL on OpenMobilityData: https://openmobilitydata.org/p/rtd-denver/611
- [x] New download URL (direct link): https://www.rtd-denver.com/files/gtfs-rt/VehiclePosition.pb
- [x] New feed information URL: https://www.rtd-denver.com/business-center/open-data/gtfs-developer-guide#gtfs-realtime-feeds

**Comment by Cristhian-HA** [comment]
Hello @wmcb91 

Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
