### ISSUE TITLE
BKK GTFS must be downloaded by https

### ISSUE THREAD

**Issue by gtfs0** [OpenMobilityData/OpenMobilityData-Public#527]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://openmobilitydata.org/p/bkk/42
- [ ] New download URL (direct link): https://www.bkk.hu/gtfs/budapest_gtfs.zip

It seems that OpenMobilityData tries to download the feed by http, therefore it doesn't work. It **must** be downloaded by https.

**Comment by Cristhian-HA** [comment]
Hello @gtfs0 
Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
