### ISSUE TITLE
Sun Tran Data Issue

### ISSUE THREAD

**Issue by Leefun2014** [OpenMobilityData/OpenMobilityData-Public#528]
## NEW FEEDS: 

To submit **new** feeds, visit [Submit a Feed](https://transitfeeds.com/submit).

Note that if you click on **Submit a Feed** on a location or provider details page, the location and provider will be automatically populated.

At this time we can only accept static, unchanging URLs. Maintenance of dynamic URLs is proving too difficult and time-consuming.

## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [x] URL on OpenMobilityData: https://transitfeeds.com/p/suntran-tucson/584
- [x] New download URL (direct link): https://www.suntran.com/developers_feed.php

If application:

- [ ] New feed information URL: _________________________

**Comment by Cristhian-HA** [comment]
Hello @Leefun2014 
Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.

Have a great day!
