### ISSUE TITLE
Update feeds for Metropolitan Tulsa Transit Authority

### ISSUE THREAD

**Issue by BalooUriza** [OpenMobilityData/OpenMobilityData-Public#530]
## UPDATE EXISTING FEED:

Please fill out the following if an existing feed has a new download URL:

- [ ] URL on OpenMobilityData: https://openmobilitydata.org/p/tulsa-transit/521
- [ ] New download URL (direct link): http://gtfs.tulsatransit.org/google_transit.zip

If application:

- [ ] New feed information URL: http://gtfs.tulsatransit.org/

**Comment by Cristhian-HA** [comment]
Hello Paul,
Thank you for sending the new updates. We have made the changes on our side. Please take note that the new changes can take up to 24hrs to display. If you encounter any problems please re-open this issue.
Have a great day!
