### ISSUE TITLE
Barcelona data feed

### ISSUE THREAD

**Issue by joriswu** [OpenMobilityData/OpenMobilityData-Public#66]
Barcelona is here : http://www.tmb.cat/ca/com-obtenir-les-dades
You need to register first. I use the data and it is good.

**Comment by HendX** [comment]
Thanks Joris - I'd like to add this feed, but the application form to access the data is a bit onerous (need to submit government ID number and a presentation on how you'd use the data).

**Comment by canales** [comment]
Added.
