### ISSUE TITLE
Jefferson Lines in 13 US states

### ISSUE THREAD

**Issue by joriswu** [OpenMobilityData/OpenMobilityData-Public#80]
Jefferson Lines serves arkansas,iowa,kansas,minnesota,missouri,montana,north dakota,oklahoma,south dakota,wisconsin,wyoming in the US

http://webstore.jeffersonlines.com/gtfs/jefferson.zip

http://lockmedia.com/gtfs/feeds.asp shows an index of the feeds provided / hosted by them.

**Comment by mldickens** [comment]
This file was last updated in late 2014. While it has been set up to be valid until 2024, it doesn't include exceptions for holidays, etc. for each year. I also can't find any evidence of public linking of this file, so I'm not sure if it's actually kept up to date.
