### ISSUE TITLE
Add Angers GTFS data

### ISSUE THREAD

**Issue by MilleMiles** [OpenMobilityData/OpenMobilityData-Public#87]
Available from here:
http://data.angers.fr/donnees/mobilite-horaire-de-passage-theorique/

**Comment by HendX** [comment]
For some reason they distribute in .rar format, which TransitFeeds isn't set up to handle at this time

**Comment by mldickens** [comment]
Looks like this is in zip now. I added it on the test environment and only one stop is detected - looks like something is wrong with their stops.txt

**Comment by HendX** [comment]
There seems to be 4 different files available of varying size. I'm not sure what the difference is. Also, they don't seem to follow the spec in that there are multiple feeds within the zips.
