### ISSUE TITLE
Feed discovery API

### ISSUE THREAD

**Issue by nalbion** [OpenMobilityData/OpenMobilityData-Public#9]
Great site!  

I think it might help help consuming applications if there was an API that could return all feeds (feed IDs) that covered a specific location.  The service host would have to determine the bounding rectangle/polygon of the stops in each feed, and then allow an optional parameter(s) in the API (getFeedVersions?) to specify the lat/long to filter search results.

Users would be able to take their phone on holiday to another city, and their app could let them know what feeds are available in that city.

**Comment by caywood** [comment]
Quentin's earlier comment makes sense. I can think of use cases for "discover feeds near a point", but if people use that as a substitute for coding their app properly, providing that kind of feed discovery service will be expensive.
