### ISSUE TITLE
Add Brest GTFS data

### ISSUE THREAD

**Issue by MilleMiles** [OpenMobilityData/OpenMobilityData-Public#90]
Available from here:
https://geo.pays-de-brest.fr/actualites/Pages/public/Offre_Theorique_Bibus.aspx

**Comment by HendX** [comment]
I've set this up on the site, but for some reason the file doesn't download cleanly, so I need to investigate an issue with the downloader before it is available.

**Comment by Manu1400** [comment]
- [x] COUNTRY: France

- [x] REGION: Bretagne

- [x] CITY: Brest

- [x] DIRECT DOWNLOAD URL: https://applications002.brest-metropole.fr/VIPDU72/GPB/Lot_BrestMetropole_Bibus.zip
  This is the URL of the GTFS zip
  
- [x] FEED ACCESS INFO:  https://geo.pays-de-brest.fr/actualites/Pages/public/Offre_Theorique_Bibus.aspx
Licence "Licence Ouverte-Open Licence". Source : https://geo.pays-de-brest.fr/usages/Pages/Conditions-utilisation.aspx

- [x] This feed is reliably updated

- [x] This is an official feed

Note: Wikipedia article about this network : https://fr.wikipedia.org/wiki/Bibus_(r%C3%A9seau_de_transport)

**Comment by HendX** [comment]
This already exists here: https://transitfeeds.com/p/bibus/593

Or is there a difference that I've missed?
