### ISSUE TITLE
Deutsche Bahn long-distance lines for Germany

### ISSUE THREAD

**Issue by patrickbr** [OpenMobilityData/OpenMobilityData-Public#95]
http://patrickbrosi.de/de/projects/dbgtfs

The feed is updated regularly from the DB API.

**Comment by HendX** [comment]
Thanks Patrick - I'm a bit torn on whether to add this, as my preference is for TransitFeeds to publish only official feeds. I know there are some non-official feeds on here, but I would like to remove those eventually.

I'll leave this open for now, and thanks for requesting the addition.

**Comment by patrickbr** [comment]
Ok, I totally understand your concerns. Thanks!
